---
lang: sv
title: Alla arbetsblad
---

## Arbetsblad som används respektive vecka

### Vecka 1: Introduktion och mål

  - [Rathus (1973) självskattningsskala för självhävdelse (PDF)](forms/100respekt-Rathus-svenska.pdf){.bi-filetype-pdf}
  - [Självskattning av grad av självhävdelse (PDF)](forms/100respekt-skattning-situation-relation.pdf){.bi-filetype-pdf}
  - [Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf){.bi-filetype-pdf}
  - [Exempel 1: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-1-SMARTa-mal.pdf){.bi-filetype-pdf}

### Vecka 2: En grund för nyinlärning

  - [Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel 1: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-1-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Kartläggning av obehag och motivation (PDF)](forms/100respekt-obehag-motivation-reflektion.pdf){.bi-filetype-pdf}
  - [Planera för framgång (PDF)](forms/100respekt-planera-traning.pdf){.bi-filetype-pdf}

### Vecka 3: Bli medveten om tänkandet

  - [Planera för framgång (PDF)](forms/100respekt-planera-traning.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-2-SMARTa-mal.pdf){.bi-filetype-pdf} 
  - [Hindrande antaganden för konstruktiv självhävdelse (PDF)](forms/100respekt-hindrande-antaganden-sjalvhavdelse.pdf){.bi-filetype-pdf}
  - [Mina rättigheter att hävda mig själv (PDF)](forms/100respekt-mina-rattigheter.pdf){.bi-filetype-pdf}
  - [Mina skäl att utföra beteendeexperiment (PDF)](forms/100respekt-mina-skal-beteendeexperiment.pdf){.bi-filetype-pdf}
  - [Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf){.bi-filetype-pdf}
  - [Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf){.bi-filetype-pdf}

### Vecka 4: Bli medveten om handlandet

  - [Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-2-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)

### Vecka 5: Bli medveten om kroppen

  - [Planera för framgång (PDF)](forms/100respekt-planera-traning.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Mina sätt att sänka spänningsnivån (PDF)](forms/100respekt-avslappningstekniker.pdf){.bi-filetype-pdf}
  - [Manus för progressiv avslappning (PDF)](forms/100respekt-manus-progressiv-avslappning.pdf){.bi-filetype-pdf}

### Vecka 6-7: Säga nej, hantera kritik, hantera besvikelser, hantera komplimanger

  - [Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-2-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Hindrande antaganden om att säga ’nej’ (PDF)](forms/100respekt-hindrande-antaganden-saga-nej.pdf){.bi-filetype-pdf}
  - [Hjälpande antaganden om att säga ’nej’ (PDF)](forms/100respekt-hjalpande-antaganden-saga-nej.pdf){.bi-filetype-pdf}
  - [Hindrande antaganden om att ta/ge kritik (PDF)](forms/100respekt-hindrande-antaganden-hantera-kritik.pdf){.bi-filetype-pdf}
  - [Hjälpande antaganden om att ta/ge kritik (PDF)](forms/100respekt-hjalpande-antaganden-hantera-kritik.pdf){.bi-filetype-pdf}
  - [Hindrande antaganden om att hantera besvikelser (PDF)](forms/100respekt-hindrande-antaganden-hantera-besvikelser.pdf){.bi-filetype-pdf}
  - [Hjälpande antaganden om att hantera besvikelser (PDF)](forms/100respekt-hjalpande-antaganden-hantera-besvikelser.pdf){.bi-filetype-pdf}
  - [Hindrande antaganden om att ta/ge komplimanger (PDF)](forms/100respekt-hindrande-antaganden-hantera-komplimanger.pdf){.bi-filetype-pdf}
  - [Hjälpande antaganden om att ta/ge komplimanger (PDF)](forms/100respekt-hjalpande-antaganden-hantera-komplimanger.pdf){.bi-filetype-pdf}

### Vecka 8: Planera för framkomlighet

  - [Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-2-SMARTa-mal.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf){.bi-filetype-pdf} (att fortsätta jobba med)
  - [Rathus (1973) självskattningsskala för självhävdelse (PDF)](forms/100respekt-Rathus-svenska.pdf){.bi-filetype-pdf}
  - [Självskattning av grad av självhävdelse (PDF)](forms/100respekt-skattning-situation-relation.pdf){.bi-filetype-pdf}
  - [Så här vill jag fortsätta hävda mig själv konstruktivt (PDF)](forms/100respekt-vidmakthallande-reflektion.pdf){.bi-filetype-pdf}
