---
lang: sv
title: Alla media för progressiv avslappning
---

Följande material utgår från @michel2008 och är utökat med instruktioner från @ost2006tillampad.

## Arbetsblad

- [Planera för framgång (PDF)](forms/100respekt-planera-traning.pdf){.bi-filetype-pdf}
- [Manus för progressiv avslappning (PDF)](forms/100respekt-manus-progressiv-avslappning.pdf){.bi-filetype-pdf}

::: {.content-visible when-format="html"}
## Instruktioner, video

{{< video https://www.youtube.com/embed/8ygZeRNVdIU >}}

{{< video https://www.youtube.com/embed/Sfpfa75e93k >}}

## Instruktioner, enbart ljud

### Progressiv avslappning, del 1

<audio controls=""><source src="https://www.dropbox.com/s/66gviwf37y12ot9/KSH-06-progressiv-muskelavslappning-del-1.mp3?raw=1" type="audio/mpeg" />Din webbläsare stödjer inte uppspelning av ljudfiler.</audio>

### Progressiv avslappning, del 2

<audio controls=""><source src="https://www.dropbox.com/s/7znxp4ac5m655zu/KSH-06-progressiv-muskelavslappning-del-2.mp3?raw=1" type="audio/mpeg" />Din webbläsare stödjer inte uppspelning av ljudfiler.</audio>

### Progressiv avslappning, kort version

<audio controls=""><source src="https://www.dropbox.com/s/wa55oouszt68ikh/KSH-06-progressiv-muskelavslappning-kort.mp3?raw=1" type="audio/mpeg" />Din webbläsare stödjer inte uppspelning av ljudfiler.</audio>

### Ladda ned instruktioner (mp3)

- [Progressiv avslappning, del 1 (mp3)](https://www.dropbox.com/s/66gviwf37y12ot9/KSH-06-progressiv-muskelavslappning-del-1.mp3?dl=1){target="_blank" .bi-filetype-mp3}
- [Progressiv avslappning, del 2 (mp3)](https://www.dropbox.com/s/7znxp4ac5m655zu/KSH-06-progressiv-muskelavslappning-del-2.mp3?dl=1){target="_blank" .bi-filetype-mp3}
- [Progressiv avslappning, kort version (mp3)](https://www.dropbox.com/s/wa55oouszt68ikh/KSH-06-progressiv-muskelavslappning-kort.mp3?dl=1){target="_blank" .bi-filetype-mp3}
:::