---
lang: sv
title: Licens och källkod
---

## Licensvillkor {#sec-licens}

Materialet är fritt tillgängligt att använda som självhjälpsmaterial och i psykologisk behandling. Vi har valt en fri dokumentlicens eftersom vi vill att psykologiska interventioner som utvecklats och utvärderats med offentliga medel ska vara fritt tillgängliga för allmänheten, liksom i primärvården och psykiatrin.

Detta verk är en av upphovsrättsinnehavaren [Centre for Clinical Interventions, Government of Western Australia](https://www.cci.health.wa.gov.au/) till originalet auktoriserad anpassning och utökning av @michel2008 (som är ett så kallat "public domain"-verk). 

Svensk anpassning &copy; 2023 Tobias Hagberg. Detta verk är licensierat under [Erkännande-DelaLika 2.5 Sverige (CC BY-SA 2.5
SE)](<https://creativecommons.org/licenses/by-sa/2.5/se/>). Med andra ord: Du får fritt använda, anpassa och sprida det här materialet, på villkor att du anger källan @hagberg2023. 

Se @HAGBERG2023100629 för information om anpassningar och resultat av utvärdering.

## Källkod

Granska och ladda ned [källkoden till den här boken](https://github.com/hmep/r2book) från GitHub.