---
lang: sv
title: Effekter av bristande konstruktiv självhävdelse
---

Bristande konstruktiv självhävdelse föder låg självkänsla. Om du har för
vana att kommunicera på ett passivt sätt säger du inte fullt ut vad du
verkligen känner och tänker. Det betyder att du riskerar att böja dig
för andras behov och önskemål. Det innebär att du bortser från dina egna
behov och önskemål. Det kan ge en känsla av meningslöshet och av att du
själv inte är den som styr i ditt liv.

Om du inte uttrycker dig öppet, utan gömmer dina tankar och känslor, kan
det få dig att känna dig spänd, stressad och orolig. Andra kan uppfatta
dig som förbittrad. Det kan också leda till destruktiva och nedbrytande
relationer med andra. Det kan leda till att det känns som att de som
står dig närmast inte egentligen känner dig.

::: {.callout-tip}
## Boktips för dig med social ångest
Om du har social ångest, kan ett nästa steg efter att du jobbat med det här självhjälpsmaterialet
vara att skaffa självhjälpsboken [Social fobi – social ångest: effektiv hjälp med KBT](http://libris.kb.se/bib/2bzfp50b01zhhwbq){target=”_blank”} av
@Furmark2019sf. Du kan använda den
boken på egen hand, eller i terapi, med stöd av en KBT-psykolog eller
-psykoterapeut.
:::

Brist på självhävdelse är mycket vanligt bland dem med social ångest. Personer
med social ångest har en tendens att utgå från att andra personer är dömande och
kritiska mot dem och undviker därför ofta sociala situationer.

Om du nästan alltid kommunicerar på ett aggressivt sätt kan du så
småningom förlora kontakten med vänner och personer i din närhet kan
tappa respekten för dig. Även det här kan leda till dålig självkänsla.

Det finns mycket forskning om de negativa effekterna av bristande
konstruktiv självhävdelse -- det vill säga överskott på passiv eller
aggressiv kommunikation. Personer som hävdar sig själva konstruktivt har
generellt sett mindre problem med depression och lever friskare liv.
Personer som har brister i självhävdelse löper större risk att hamna i
alkohol- eller drogmissbruk.
