---
title: Konstruktiv självhävdelse är något vi lär oss
---

Förmågan att hävda sig själv är ett resultat av inlärning, både av sätt
att bete sig och sätt att tänka. Vi föds alla med en hög grad av
självhävdelse. Tänk på nyfödda som skriker när de behöver något --
bebisar uttrycker sina känslor utan spärrar. Med tiden anpassar de
gradvis sina beteenden, så att de ska passa med de svar de får från
omgivningen, det vill säga de responser de får från familjen och så
småningom från kompisar, auktoritetsfigurer, arbetskamrater och så
vidare. Om det till exempel var vanligt att i din familj hantera
konflikter med gormande och grälande så kan du själv ha kommit att
lära dig att hantera meningsskiljaktigheter på det sättet. Du kan också
ha svårt att hävda dina behov om du under din uppväxt lärde dig att du
alltid skulle tillfredsställa andras behov, snarare än dina egna. Och om
det i din familj eller bland dina närmaste fanns en norm som sa att man
inte skulle uttrycka negativa känslor så kanske du blev ignorerad eller
förminskad om du ändå gjorde det. Då lärde du dig snabbt att inte
uttrycka negativa känslor.

Här är några frågor som kan vara bra att ställa till dig själv när du
tänker på hur du kan ha lärt dig att inte hävda dina behov.

-   Hur hanterade din familj konflikter?
-   Vad gjorde dina familjemedlemmar när de inte höll med någon eller
    var arga på andra personer?
-   Hur lärde dina föräldrar dig att hantera konflikter?
-   Vad förmedlade de för budskap till dig med sina egna beteenden?
-   På vilket sätt lärde du dig att få det du ville ha utan att fråga om
    det direkt? (Exempel på indirekta sätt kan vara att gråta, bråka,
    hota och så vidare.)
-   Använder du något av de sätten för att få som du vill idag?

Som du ser av exemplen ovan så finns det ofta begripliga och giltiga
skäl till att du har svårt för att hävda dig själv konstruktivt. Som
barn och tonåringar lärde vi oss att bete oss på sätt som fungerade för
oss i stunden. Om vi stod upp mot aggressiva föräldrar eller vänner kan
det ha lett till problem i de situationerna. Då lärde vi oss att hålla
oss under radarn istället. Eller så lärde vi oss att själva vara
aggressiva för att överleva. Och det är troligt att de familjemedlemmar
eller vänner som lärde oss det här också själva i sin tur hade lärt sig
det från andra.

Det är viktigt att du inte klandrar dig själv eller din familj för att
du kämpar med att hävda dig själv. Det kan vara hjälpsamt att tänka att
du och din familj har varit fast i en ond spiral. Nu har du beslutat dig
för att bryta mönstret och lära dig nya sätt att tänka och nya sätt att
hävda dig själv konstruktivt. Det betyder att du inte kommer att
förmedla vidare de ohjälpsamma beteendena till dina egna
familjemedlemmar och vänner.
