---
lang: sv
title: "Övning: Hur bra är du på att hävda dig själv?"
---

Det kan vara svårt att avgöra hur bra du är på att hävda dig själv. I
vissa situationer kanske du känner dig mycket kapabel, men i andra
situationer kan du märka att du faktiskt inte uttrycker hur du känner
eller tänker, eller blir upprörd eller frustrerad.

## Skatta din grad av självhävdelse i specifika situationer/relationer

I den här övningen får du hjälp att skatta hur bra du är på att hävda
dig själv konstruktivt i olika situationer. Det hjälper dig att
identifiera de områden i livet som du kan utveckla din
självhävdelseförmåga i. 

Lägg den tid du behöver på att fylla i arbetsbladet, även om det kan kännas
jobbigt att ta ställning till så många olika kombinationer av situationer och
relationer. Du kommer ha igen arbetet när det blir dags att utvärdera dina
framsteg. Om du under eller efter övningen känner dig trött eller ledsen, ge dig
själv ett erkännande att du just nu gör ett viktigt arbete.

::: {.content-visible when-format="html" .form}
[Självskattning självhävdelse (PDF)](forms/100respekt-skattning-situation-relation.pdf)
:::
\xqrform{Självskattning självhävdelse (PDF)}{forms/100respekt-skattning-situation-relation.pdf}

## Skatta även din allmänna grad av självhävdelse

Följande skattningsskala är en svensk anpassning av @Rathus1973 självskattningsskala för självhävdelse i allmänhet. Följande skattningsskala är en svensk anpassning av @Rathus1973 självskattningsskala för självhävdelse i allmänhet. I en studie fann @GUSTAFSON1992 ett medelvärde på 4,0 respektive 4,1 (standardavvikelse 6,0 för båda) i två svenska stickprov med en ej publicerad svensk översättning av skalan. @Thompson2011 fann ett medelvärde på 6,2 (standardavvikelse 23,9) i ett amerikanskt icke-kliniskt stickprov med studenter och det engelskspråkiga originalet. Vilken totalpoäng får du?

::: {.content-visible when-format="html"}
[Rathus (1973) självskattningsskala för
självhävdelse (PDF)](forms/100respekt-Rathus-svenska.pdf)
:::
\xqrform{Rathus (1973) självskattningsskala för
självhävdelse (PDF)}{forms/100respekt-Rathus-svenska.pdf}

När du har gått genom nästan hela självhjälpsmaterialet kommer du att i vecka 8 få följa upp din egen
utveckling genom att göra om de här skattningarna. När du jämför dina svar från starten av perioden med
dem från slutet av den kommer du att få svart på vitt hur det har gått för dig.
