---
lang: sv
title: "Övning: Formulera dina första mål för din träning i självhävdelse"
---

Under de kommande veckorna kommer du att få träna på att hävda dig själv
konstruktivt i situationer som brukar bli besvärliga. Vilket område vill
du börja träna inom? Du kommer strax att få formulera en egen
målsättning.

::: {.content-visible when-format="html"}
{{< video https://www.youtube.com/embed/fAlPVh76lHI >}}
:::
\xqr{Vad tycker du är svårt? (Youtube)}{https://youtu.be/fAlPVh76lHI}

## Vad är ett ”SMART” mål?

När du nu formulerar ditt eget mål, använd formeln ”SMART”. Med det
menas målet så långt det är möjligt bör vara S) specifikt, M) mätbart,
A) acceptabelt (i meningen nåbart, *attainable* på engelska), R) realistiskt och T) tidssatt.
Här är några exempel på mer eller mindre SMARTa målsättningar:

-   *”Mitt mål är att säga nej till min chef när hen frågar om jag kan
    arbeta över på onsdagar och torsdagar under de kommande 8
    veckorna.”*
    -   S? Är målet specifikt? Ja!
    -   M? Är det mätbart? Ja, det går att räkna antal gånger personen
        säger nej till chefen.
    -   A? Är det nåbart? Ja, om du har formellt mandat att säga ifrån.
    -   R? Är det realistiskt? Ja, om det är sannolikt att chefen
        faktiskt kommer att be personen att jobba över.
    -   T? Är det tidssatt? Ja, det gäller vissa dagar (onsdagar och
        torsdagar) under en begränsad tid (8 veckor).
-   *”Mitt mål är att säga ’Jag älskar dig’ till min partner 3 gånger
    under veckan som kommer”*
    -   Utvärdera själv om målet är SMART!
-   *”Mitt mål är att under de kommande 4 veckorna knacka på hos
    grannen och att utan att tappa humöret och börja skälla förklara att
    jag har svårt att sova på grund av den höga ljudvolymen, varje gång
    grannen spelar högt på stereon efter 22:30 på vardagskvällar”*
    -   Utvärdera själv om målet är SMART!
-   *”Mitt mål är att sluta vara så mesig och ta mig i kragen i sociala
    sammanhang”*
    -   Tänk efter -- tycker du att det här målet var särskilt SMART?
        Varför inte?

När du formulera ditt mål på formeln SMART gör du det det möjligt för dig själv
att märka när du har uppnått det. Det kopplar loss utvärderingen från ”hur det
känns” -- ibland kan man framgångsrikt göra något svårt och viktigt fast det
inte alls känns roligt när man gör det. Ett SMART mål gör det på så sätt möjligt
för dig att registrera både bakslag och framgångar med lite distans till
känslorna. Kanske känns det provocerande att minska betydelsen av känslorna. Kom
då ihåg att det på inget sätt betyder att känslorna är oviktiga. Anledningen är
helt pragmatisk: För att klara av att börja träna på en färdighet som är
förenlig med något du själv tycker är viktigt kan det ofta vara hjälpsamt att
låta känslorna vara som de är, utan att kämpa mot dem. Beteenden är trots allt
väldigt mycket lättare att förändra än känslor. Genom att göra det du vill kan
du på lite sikt också förändra de känslomässiga aspekterna av upplevelsen --
antingen genom att du blir bättre på att tolerera dem, och/eller att du faktiskt
märker att du inte reagerar lika starkt längre.

Under kommande veckor kommer du att få hjälp med att hantera både mot- och medgångar
(såväl praktiska som känslomässiga) på ett sätt som ökar chansen att du kommer
att orka fortsätta träna på det som du tycker är både viktigt och svårt.

## Dina egen mål

Nu är det din tur. Ta hjälp av kartläggningen du gjorde nyss, och formulera ett
eller några första egna mål för högre grad av konstruktiv självhävdelse. Ge dig själv lite tid att hitta
mål som är lagom svåra -- med det menas att de ska vara realistiska men
samtidigt utmanande och aningen ångestväckande. Det är när du handlar på ett
sätt som du vill, trots visst obehag, som du ger dig själv en chans till
nyinlärning och kan bredda din beteenderepertoar.

Som du ser i arbetsbladet nedan finns det flera kolumner att fylla i. Precis just nu räcker det med att du fokuserar på de två första, längst till vänster. Du behöver inte komma på en lång lista med mål just nu -- det räcker med ett enda för att du ska komma igång med ett viktigt arbete. Så sänk kraven!

::: {.content-visible when-format="html"}
[Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf)
:::

\xqrform{Mina mål: Självhävdelsebeteenden att öka (PDF)}{forms/100respekt-SMARTa-mal.pdf}

::: {.content-visible when-format="html"}
[Exempel 1: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-1-SMARTa-mal.pdf)
:::

\xqrform{Exempel 1: Mina mål: Självhävdelsebeteenden att öka (PDF)}{forms/100respekt-exempel-1-SMARTa-mal.pdf}

