---
lang: sv
title: Din måluppfyllelse just nu
---

Du formulerade nyss en personlig målsättning med programmet. Du skrev så
här:

##4f1b5b6c8b7a92eb516892f5f44e84e7=

## Hur väl tycker du att du just ny lever upp till målet?

Hur mycket respekterar du dina egna rättigheter och hur mycket
respekterar du andras rättigheter med ditt målbeteende (det du vill
jobba med) i nuläget? Även om det kanske känns svårt att sätta en siffra
på ditt eget beteenden -- försök ändå! Det är inget självändamål att det
ska kännas jobbigt, förstås, men när du ägnar tid att tänka efter
hjälper du dig själv att bli mer medveten om hur ditt handlande påverkar
både dig själv och andra. Det kommer du att ha nytta av!

##97190e70ad78f90ba1381af2ca685afb=

## Utvärdering av den här modulen

Puh! Nu har du fått jobba mycket. Kom ihåg att belöna dig själv för dina
ansträngningar -- särskilt om något har varit svårt. Kom också ihåg att
trägen vinner, som ordspråket heter. Vi som ligger bakom det här
programmet vet av egen erfarenhet att det är tufft att arbeta med att
förändra beteenden och att det ofta kan kännas svårt att utmana sig
själv. Kom ihåg: Det arbete du redan har gjort kommer ligga till grund
för dina framsteg under de kommande veckorna. Du förtjänar ett
erkännande för det!

##f30ac36eb016e6810ea6a4a296b349f0=

 
::: {.callout-note}
## Om nästa modul

I nästa modul går genom vad som kännetecknar de aggressiva, de
konstruktivt självhävdande och de passiva kommunikationsstilarna. Varje
stil har sina egna förtjänster och kostnader. Vi smygstartar också ett
spår med avslappningsövningar som vi kommer att komma tillbaka till i
modul 5. Genom att sänka den allmänna spänningsnivån blir det lättare
att vara medvetet närvarande i vardagen. Det ökar förmågan att agera på
ett sätt som är konstruktivt även när den första impulsen är passiv
eller aggressiv kommunikation.

Med respekt i kvadrat,

/Patrik & Tobias
:::