---
lang: sv
title: Sammanfattning och återkoppling på innehållet
---

-   Det är en viktig hävda sig själv-färdighet och en viktig social
    färdighet att kunna ta emot och ge komplimanger.
-   Som med andra färdigheter för konstruktiv självhävdelse kan det
    finnas hindrande tankar som gör det svårt för dig att ta emot en
    komplimang på ett vänligt sätt. Du kan utmana och balansera det
    hindrande tänkandet genom att ge dig tid och struktur för att hitta
    nya, alternativa tankar.
-   Det är också användbart att kunna visa sin vänlighet mot andra genom
    att kunna ge komplimanger.
-   Vi behöver alla regelbundet öva på att ta emot och ge komplimanger.
    Det kan ha en väldigt positiv inverkan på vår egen självkänsla,
    liksom på självkänslan hos dem vi har omkring oss.

## Hur har du det precis just nu?

Nu går vi in i sista veckan i det här självhjälpsmaterialet i
konstruktiv självhävdelse. Det är inte slutet på din resa, det här
är bara sluten på allra första början.

Hur har du det precis just nu?

-   Kanske är du nöjd och stolt över alla beteendeexperiment och
    alla nyupptäckter av framkomlighet i livet som du har gjort? I
    sådana fall -- dela gärna den stoltheten och glädjen med någon i
    din omgivning. Det är ett exempel på konstruktiv självhävdelse
    som verkligen också är bra för självkänslan. När man börjar
    jobba med sig själv och utmana gamla beteenden och förutsägelser
    kan man ofta känna sig extra sårbar. Då är klokt att ge sig
    själv både uppmuntran och tid och plats att återhämta sig och
    bearbeta de nya erfarenheterna. 
-   Kanske har det varit alldeles för mycket kring dig i livet för
    att du ska ha hunnit engagera dig så mycket som du hade önskat.
    I sådana fall -- skänk dig själv en tacksamhetens tanke för att
    du har klarat av att prioritera det som har varit verkligt
    viktigt för dig. Det är också konstruktiv självhävdelse i
    praktiken! Känner du dig uppjagad och spänd? Ta också tillfället i
    akt att **[göra några av
    avslappningsövningarna](https://www.iterapi.se/sites/respekt/program/5-hitta-dina-s-tt-att-s-nka-sp-nningsniv-n)**.
-   Kanske har du ändå dåligt samvete, för att du vet med dig att du
    mer än du skulle ha önskat har undvikit det obehag som
    ofrånkomligen kommer av att ta tag i saker som är svåra. Ge dig
    i sådana fall ordentligt med självmedkänsla. Det obehag du har
    känt är en påminnelse om att **[det här sannolikt är viktigt för
    dig](https://www.iterapi.se/sites/respekt/program/3-utmana-negativa-f-ruts-gelser-med-beteendeexperiment/15-argument-f-r-att-byta-undvikande-mot-aktivt-deltagande)**.
    I det här avsnittet kommer vi att planera för hur du kan fortsätta
    jobba på egen hand, och modulerna och övningarna finns kvar här
    för dig även fortsättningsvis. Börja med att ta hjälp av
    övningarna i det här avsnittet. Kom ihåg: ett litet steg i
    värderad riktning är 100% ett steg i värderad riktning. 
-   Kanske är du besviken på oss över att det här programmet inte
    har motsvarat dina förväntningar? I sådana fall -- berätta för
    oss här nedan vad du har saknat. Att du ger oss konstruktivt
    formulerad återkoppling gör det både möjligt för dig att träna
    på konstruktiv självhävdelse precis här och nu, och ger oss en
    chans att faktiskt förbättra det här programmet till det bättre.
    Vi uppskattar din återkoppling mycket!

## Så här har jag det precis nu

##ec8dd928fef337720e0ea1b11dd8b08f=

I den här avslutande modulen ska vi sätta samma de färdigheter som
du tillägnat dig under programmets gång och stegvis visa hur du på
egen hand kan förbättra din konstruktiva självhävdelse i ditt
vardagsliv.

## Vill du ge oss en komplimang?

##54ec3893768930cbe636662be286a70f=
