---
lang: sv
title: "Övning: Upprätta en hierarki"
---

Börja med att skriva ned tio situationer som du skulle vilja bli bättre
på att hävda dig själv i och som du vill jobba vidare med på egen hand
-- i din egen takt. Det kan vara hemma, på jobbet, med vänner eller ute
bland folk.

[[Tips!]{.rlabel} Går också gärna tillbaka till och ta hjälp av de olika
modulerna i programmet, till exempel [tekniker för
självhävdelse](https://www.iterapi.se/sites/respekt/program/4-m-ngdtr-na-konstruktiv-sj-lvh-vdelse-i-vardagen)
(modul 4) och hur du [sänker spänningsnivån i
kroppen](https://www.iterapi.se/sites/respekt/program/5-hitta-dina-s-tt-att-s-nka-sp-nningsniv-n)
(modul 5). Du har också fått välja att jobba med en eller flera områden
att träna på att hävda dig själv bättre i, till exempel när du vill
[säga
'nej'](https://www.iterapi.se/sites/respekt/program/6-s-ga-nej-konstruktivt)
(modul 6), när du [får kritik eller vill ge
kritik](https://www.iterapi.se/sites/respekt/program/7-hantera-kritik-konstruktivt)
(modul 7), [när du blir besviken, men vill kunna gå vidare
ändå](https://www.iterapi.se/sites/respekt/program/8-hantera-besvikelser-konstruktivt)
(kapitel 8) och när du [får och vill ge
komplimanger](https://www.iterapi.se/sites/respekt/program/9-ge-och-ta-emot-komplimanger-konstruktivt)
(modul 9). ]{.rtip} I modul 1 fyllde du i ett [formulär med besvärliga
situationer/relationer](https://www.iterapi.se/sites/respekt/program/1-hur-h-vdar-man-sig-sj-lv-konstruktivt-/6-uppgift-hur-bra-r-du-p-att-h-vda-dig-sj-lv-).
Det innehåller flera uppslag till situationer som du kan jobba med. Gå
gärna tillbaka och se över det för att påminna dig själv om vad du
svarade.

Om du fortfarande kämpar med att identifiera situationer att arbeta med,
tänk på följande situationer. Det kan hjälpa dig. Hur brukar du göra när
...

-   maten du har beställt kommer in kall eller överlagad?
-   någon röker där rökförbud råder?
-   du vill be en vän att betala tillbaka ett lån som han eller hon har
    tagit av dig?
-   alla lämnar dig ensam med disken?
-   du irriterar dig på en vana hos någon du älskar?

Om du märker att du vanligtvis beter dig på ett passivt eller aggressivt
sätt i någon av ovanstående situationer, ta med den situationen i din
lista. Upprätta sedan en hierarki -- det vill säga att rangordna
situationerna från lättast till svårast. Gör en skattning av hur
besvärligt du upplever att det är att hävda dig själv varje situation,
från 0 till 100. En skattning om "0" betyder att situationen inte är
svår alls att hävda dig själv i. En skattning om "100" betyder att det
är den mest ansträngande uppgift du över huvud taget kan tänka dig att
utföra. Med dessa referenspunkter kan du tänka ut var situationerna på
din lista hamnar på skalan 0--100, från lättast till svårast.

## Exempel på en självhävdelse-hierarki

  ----------------------- ----------------------- -----------------------
  Situation               Skattning\              Rangordning
                          (0--100)                

  Säga till svärmor att   70                      9
  jag inte vill att hon                           
  röker inomhus.                                  

  Ringa banken och säga   50                      4
  att jag behöver mer tid                         
  för att tänka på om jag                         
  ska ta lånet eller                              
  inte.                                           

  Säga till grannen att   40                      6
  deras hund stör min                             
  nattsömn.                                       

  Säga till min partner   45                      7
  att jag vill ha en                              
  kväll i veckan för mig                          
  själv.                                          

  Säga förlåt till min    30                      3
  kollega för att jag var                         
  irritabel i onsdags.                            

  Säga till barnen att    20                      1
  göra sina sysslor                               
  hemma.                                          

  Be min vän lämna        25                      2
  tillbaka boken jag                              
  lånade ut för 3 månader                         
  sedan.                                          

  Säga till chefen att    80                      10
  jag har för mycket att                          
  göra och inte kan vara                          
  med i nya projektet.                            

  Ringa pianostämmaren    40                      5
  och säga att pianot                             
  fortfarande klingar                             
  falskt.                                         

  Säga till pappa hur     30                      4
  mycket jag älskar                               
  honom.                                          

                                                  
  ----------------------- ----------------------- -----------------------

## Din egen självhävdelsehierarki

##fe5b72f9c6ecca7cf87d99ac8760d533=
