---
title: Lägg märke till negativa förutsägelser
---

Som vi lade märke till i modul 3 finns det ofta **[hindrande
förutsägelser om hur det ska
gå](https://www.iterapi.se/sites/respekt/program/3-utmana-negativa-f-ruts-gelser-med-beteendeexperiment)**
bakom vår oförmåga att hävda oss själva. De kan handla om vilken effekt
vårt konstruktiva målbeteende ska få på oss själva eller andra, eller om
hur det kommer att kännas när vi utför vårt målbeteende. Lägg gärna lite
tid på att undersöka dina negativa förutsägelser för var och en av
situationerna du har tagit med i din hierarki.

## Ett exempel

För personen i exemplet på förra sidan som hade svårt att säga till
barnen, var det här den hindrande förutsägelsen: "Om jag tjatar på
barnen att göra sina sysslor kommer de bli irriterade på mig, då kanske
de inte tycker om mig längre eller tycker att jag är en dålig mamma."

Efter att personen gjorde sitt beteendeexperiment fann hen stöd för
följande hjälpande förutsägelse: "Alla barn blir irriterade på sina
mammor ibland, det betyder inte att de inte tycker om sina mammor. Det
är viktigt för barn att lära sig hur man gör olika sysslor. För att vara
en bra mamma måste jag ibland uppmana barnen att göra saker som de inte
gillar. De kanske tackar mig för det senare."

När personen hade fått en ny erfarenhet av att få framgång med att
utföra sitt målbeteende, blev det lättare att hävda sig i situationen,
och sedan gör det igen i nästa situation. Efter några veckors arbete med
att kommunicera rakare började personen i exemplet att känna sig
bekvämare.

## "Get out of your mind and into your life!"

[[Tips!]{.rlabel} När du har en stund över, titta gärna på det här
TedTalk-klippet på engelska med forskaren och historieberättaren Brené
Brown som berättar om hur hon sökte hjälp av en terapeut för att komma
vidare i livet. Hon säger bland annat så här: \"Sårbarhet är kärnan i
skam och rädsla och vår kamp för tillhörighet, men det är också källan
till glädje, kreativitet, samhörighet med andra och kärlek\".
]{.rtip}Ett behandlingsprogram som det här handlar på sätt och vis om
att \"nagga sina negativa förutsägelser i kanten\", ett
beteendeexperiment i taget. Ett vanligt hinder för oss människor är våra
egna sinnen. Vi är på sätt och vis för intelligenta för vårt eget bästa.
Ofta tror vi att vi både kan och måste tänka oss till rätt svar eller
rätt känsla, innan vi vågar skrida till handling. Att gå i terapi --
eller ett träningsprogram som det här -- handlar ofta om att vända på
förhållandet: att göra för att sedan få uppleva framgång. Det är bättre
än att vänta på att känna sig motiverad för att kunna göra. Med det
menas att bryta oroande och ältande (det vill säga problemlösning som
går på tomgång) genom att hämta faktiska erfarenheter i livet, i
enlighet med den **[aktiva
cirkeln](https://www.iterapi.se/sites/respekt/program/3-utmana-negativa-f-ruts-gelser-med-beteendeexperiment/15-argument-f-r-att-byta-undvikande-mot-aktivt-deltagande)**.
Ett annat sätt att uttrycka det på är: \"Get out of your mind and into
your life!\". 

## Du är inte i slutet av en resa, du är i början av en resa

Vår förhoppning med det här träningsprogrammet har varit att ge dig
några första goda erfarenheter av att testa framkomlighet i livet i
praktiken. Ta med dig av alla dina erfarenheter som du har gjort i
programmet! Det här låter kanske konstigt och till och med lite
skrämmande, men låt också din sårbarhet vara en färdkamrat. Att inför
andra människor dela med sig av vad man tänker och känner -- även om det
är känslor av ledsenhet, skuld eller ren och skär rädsla eller ångest --
ger ofta mycket stor framkomlighet. När du hävdar dig själv konstruktivt
genom att berätta för någon annan hur du har det öppnar du upp för
närhet och intimitet. Det gör att du inte är ensam.

 
