---
lang: sv
title: Om skillnaden mellan bakslag och återfall
---

När du nu fortsätter på egen hand kommer du förstås att åka på ett och
annat bakslag. Det är oundvikligt och helt naturligt: Vissa dagar är man
mer sårbar än andra och i vissa situationer är det lättare att hemfalla
åt automatiska undvikande- och flyktbeteenden än andra.

Vad menar vi med bakslag och återfall?

-   Ett **återfall** är detsamma som att sluta träna på hävda sig själv
    konstruktivt. Ett exempel vore att helt och hållet sluta träna på
    att säga nej till chefen och att återgå till att ta på sig för
    mycket på jobbet.
-   Ett **bakslag** är en tillfällig ”motgång”, kanske för att det
    kanske inte gick som du ville när du försökte säga nej i ett
    (spontant eller planerat) beteendeexperiment, kanske för att du var
    extra sårbar just den dagen. Även i bakslagen finns det viktiga
    lärdomar:
    -   Lägg märke till eventuellt sekundärt självklander som då kanske
        dyker upp, och låt det vara en påminnelse om att det du arbetar
        med är både svårt och viktigt för dig.
    -   Lägg märke till dina sårbarhetsfaktorer just den dagen. Ge dig
        själv självmedkänsla och ta hand om dig själv lite extra. Ta
        också gärna hjälp av någon nära dig -- om det så bara handlar om
        att berätta att du har det lite tufft just nu!
    -   Lägg märke till övriga hjälpande och hindrande faktorer i
        sammahanget i stort.
    -   Testa igen -- och lägg märke till att du klarar av att testa
        igen!

{{< video https://www.youtube.com/embed/BL49DRAQxV8 >}}
