---
lang: sv
title: Att skilja på verbal och icke-verbal kommunikation
---

Det är viktigt att du lär dig skilja på verbala och icke-verbala
kännetecken för de olika kommunikationsstilarna. När vi känner till
dessa kan vi lättare upptäcka passiva, självhävdande och aggressiva
beteenden både hos oss själva och hos andra.

Första steget för att förändra ett beteende är att känna igen de delar som
behöver ändras. Du kanske redan är bra på att verbalt ta upp viktiga saker på
ett självhävdande, konstruktivt sätt, men kanske är samtidigt din icke-verbala
kommunikation ofta passiv och säger emot dina verbala budskap. Om du till
exempel verbalt hävdar dig själv med att säga ”Jag tycker inte om när du gör så
där” men gör det med mycket svag röst, utan ögonkontakt och medan du skruvar
obekvämt på dig -- då kommer ditt icke-verbala beteende att underminera ditt
verbala budskap. Resultatet kan bli att mottagaren inte tar budskapet på allvar.

## Även konstruktiv självhävdelse är förknippat med kostnader

Du kommer att märka att varje sätt att kommunicera både ger utdelning
och är förknippat med kostnader. Det är viktigt att erkänna att även
självhävdande, konstruktivt beteende har ett pris. Till exempel kan
priset av att du börjar bete dig självhävdande vara att andra människor
omkring dig inte tycker om det, och visar det, eftersom de kan ha vant
sig vid att du tidigare böjde dig för deras behov och önskemål. Om du är
medveten om den möjligheten kan det kanske göra det lättare för dig att
förändra ditt beteende.

När du läser beskrivningarna som följer, tänk på vilka beteenden du
själv utför i underskott och som du vill börja göra mer av!
