---
lang: sv
title: Lite om inlärning, obehag och motivation
---

\label{sec-motivation}

Innan vi börjar träning i progressiv avslappning vill vi först säga något om
inlärning och motivation, liksom om ångest och obehag -- obehag och motivation
kan hänga ihop på sätt som ofta inte känns helt intuitiva till en början.

## Varierad övning ger färdighet

Albert Einstein lärde sig inte matematik bara genom att lösa ett enda
matematiktal i grundskolan, Annika Sörenstam lärde sig inte behärska den
perfekta golfsvingen första gången hon ställde sig på driving range. Båda gjorde
precis som vi andra gör när vi lär oss något ordentligt -- de tragglade, övade
och gnatade i oöverblickbart många situationer. 

Så är det även för den som lär sig progressiv avslappning och att bli bättre på att hävda sig i svåra situationer. För att du till exempel ska bli så bra på avslappning att det hjälper dig att
sänka den allmänna spänningsnivån gäller det att du gör övningarna ofta och i
många situationer: på bussen, på promenaden, på jobbet, när du är lugn, när du
känner dig stressad, när det är roligt att göra det, när det känns motigt, när
du är ensam, när du är bland människor, och så vidare.

Enligt aktuell forskning [@Craske2008] maximerar du inlärningen om du
skapar variation, exempelvis gör avslappningsövningarna \...

-   på olika platser
-   vid olika tidpunkter -- morgon, middag, kväll \...
-   i olika känslotillstånd
-   med olika stressnivå
-   ensam eller bland andra
-   med olika \... ja, du förstår: så varierat som möjligt!

Och allra bäst blir inlärningen om du håller i övandet över tid. Det är
därför vi påbörjar träning i progressiv avslappning redan här i vecka 2. Du kommer att få fortsätta med den här träningen under flera veckor framöver.

Kom ihåg att samma princip för inlärning gäller för precis allt du
kommer att lära dig, både när du arbetar med konstruktiv självhävdelse och i livet i stort.

## Men vänta nu \... gäller det där med variation även obehag?

Det är en bra fråga! Svaret är ja, även om det inte känns intuitivt rätt. Men
faktum är att den allra senaste forskningen säger att det är eftersträvansvärt
att mixa och matcha träning med olika grad av ångest/obehag. Det är det som ger
nyinlärning. Utan någon form av obehag eller motstånd -- ingen nyinlärning. Och
utan nyinlärning består de gamla besvären.

Den här filmen på engelska med psykologen Carol Dweck förklarar skillnaden
mellan *growth mindset* och *fixed mindset*, det vill säga olika sätt att se på
förmåga och inlärning. Ett *fixed mindset* är det självbesegrande antagandet att
förmåga (exempelvis intelligens, men det gäller även exempelvis förmågan att
hävda sig) är medfödd och oföränderlig. Ett *growth mindset*, däremot, är det
för utveckling hjälpande antagandet att förmåga är resultat av varierad och
repeterad inlärning, även i situationer när det är motigt [@dweck2006mindset].

::: {.content-visible when-format="html"}
{{< video https://www.youtube.com/embed/Yl9TVbAal5s >}}
:::

\xqr{Carol Dweck -- How To Help Every Child Fulfil Their Potential (Youtube)}{https://youtu.be/Yl9TVbAal5s}

Det är när du känner lagom mycket obehag som du lär dig allra bäst och snabbast.
Tänk tillbaka: Hur var det för dig när du lärde dig division och multiplikation?
Att cykla? Du kommer att få jobba mycket mer med dina egna antaganden kring det
du tycker är svårt i vecka 3 och framåt.

Känns det jobbigt när du läser det här? Du behöver inte uppsöka maximalt obehag.
Det räcker gott att börja anamma en mer *förlåtande* och
*accepterande* inställning till dig själv i alla de situationer som
redan nu leder till olika grad av ångest. Det är ett bättre sätt att hantera
svårigheter än att till exempel döma sig själv för att det är jobbigt.

Vi vill uppmana dig att medan du jobbar med självhjälpsmaterialet lägga märke till om du
börjar klandra dig själv för att du har känt obehag när du har gjort något svårt
(som att säga nej på ett konstruktivt sätt, eller att säga vad du tycker i ett
socialt sammanhang). Om du märker att du tänker saker som ”jag kommer aldrig
klara av gå genom hela materialet” eller ”det spelar ingen roll hur mycket jag
försöker, det går åt h-vete i alla fall” -- påminn dig då om att ångesten du
kände när du stannade kvar i den där jobbiga situationen är ett kvitto på att du
lade en byggsten i utvecklandet av en ny och bredare beteenderepertoar.

Passa även gärna på att **ge dig själv en belöning** för att du gjorde något
svårt. Du är värd all uppmuntran du kan få, inte minst den som bara du kan ge
dig själv.

## Om självförtroende och motivation

Det är inte alltid så lätt att hålla styrfart när man börjar träna på
något. Kanske går det bra den första tiden, sedan stöter man på en
motgång, och då tappar man självförtroende och lägger av. Eller är
dåligt självförtroende kanske *detsamma* som att lägga av?

## Kartläggning av obehag och motivation

Ägna en minut eller två åt att rannsaka dina upplevelser. Vilken känsla är det som
dyker upp i situationer som är svåra? Säger den känslan dig något mer än det
du kanske trodde allra först? Kanske är det så att ångesten inför en social tillställning
säger dig att du inte vill bli avvisad -- det vill säga att det påminner dig om att
gemenskap och samhörighet är verkligt viktigt för dig? Då blir följande fråga besvärlig: Vilket beteende hjälper
dig närmare det som är viktigt för dig -- att stanna hemma eller att erkänna
ångesten behöver få följa med till tillställningen? Skulle du kunna säga ’ja’ till att ångesten får hänga med när du går på tillställningen (tillsammans med all den självmedkänsla du kan uppbåda)?

::: {.content-visible when-format="html"}
[Kartläggning av obehag och motivation (PDF)](forms/100respekt-obehag-motivation-reflektion.pdf){.bi-filetype-pdf}
:::

\xqrform{Kartläggning av obehag och motivation (PDF)}{forms/100respekt-obehag-motivation-reflektion.pdf}
