---
lang: sv
title: "Övning: Påbörja träning i progressiv avslappning"
---

\label{sec-progressiverelaxation}

Målet med det här avsnittet är att dubbelt: både att lära dig att
**känna igen spänning i kroppsdelar** som du kanske inte ens vet om att
du spänner i olika situationer (det är betydligt vanligare än man brukar
tro -- det vet vi som skapat det här materialet, av egen erfarenhet) och
att genom träning i avslappning **sänka den allmänna spänningsnivån** i
vardagen. Det minskar risken att olika situationer ska bli
besvärliga och ökar chansen att du klarar av besvärliga situationer på
ett bra sätt. Tekniken vi lär ut här heter *progressiv avslappning* och
är en avslappningsmetod som i forskning har visat sig ge goda resultat
vid såväl ångestproblemen som stress.

## Från 20 minuter till 20 sekunder till 2 sekunder

Ordet *progressiv* betyder ungefär ”gradvis framåtskridande”. Tanken
med träning i progressiv avslappning är att du ska få möjlighet att bli
allt bättre på att märka när du är spänd och att sänka spänningsgraden i
stunden. Till en början tar del 1 och 2 sammanlagt cirka 20 minuter att
genomföra, men med övning kommer du att bli skickligare och skickligare
på att slappna av i de delar av kroppen som är spända. Det som idag tar
20 minuter kan med träning ta 20 sekunder eller ännu mindre. Genom att
göra övningarna och samtidigt tänka ”Slappna av” (eller någon annan
självinstruktion som känns bra för dig) samtidigt som du slappnar av i
spända muskelgrupper, kan du kanske till slut vinna färdigheten att
slappna av i hela kroppen bara genom att ta ett andetag och tyst säga
din självinstruktion. Det är en färdighet som du kan bära med dig
överallt!

## Mål 1: Identifiera spänning i kroppsdelar

Tankar, känslor, beteenden och kroppssensationer hänger ofta ihop på
ett omedvetet sätt. Det finns nästan alltid olika kroppsliga uttryck för
spänning ”inbakad” i upplevelsen av en situation, exempelvis spända
käkar, förhöjd andningsfrekvens, spända ryggmuskler och så vidare. Det
gäller mycket sannolikt även för dig, oavsett om du söker hjälp med
explosiv ilska, social ångest, stress/utmattning eller något annat.

Under tiden som du tränar på progressiv avslappning kommer du att märka
att du blir bättre på att identifiera var du är spänd i kroppen. När du
slappnar av i spända muskelgrupper ”öppnar du dörren” till ditt lite
mer medvetna jag, och kan välja att rikta uppmärksamheten mot det som är
viktigt i stunden.

Metoden för att lära sig känna igen spänning är mycket enkel: Du
kommer systematiskt få gå genom olika delar av kroppen och progressivt
(en i taget) **spänna** och sedan **slappna av** i olika muskelgrupper.
Genom att du gör detta många gånger kommer du på sikt att allt mer
automatiserat kunna lägga märke till spänning.

## Mål 2: Sänka den allmänna spänningsnivån

Genom att träna på att sänka spänningsnivån så sänker du samtidigt
spänningsnivån i kroppen. Ju mer du övar, desto större blir effekten.

Det kan vara mycket svårt att lägga märke till att man är spänd. Men om
du någon gång har haft problem som exempelvis nackont, ryggskott eller
spänningshuvudvärk, så vet du att oupptäckt spänning som har fått pågå
för länge kan begränsa livet rejält, ibland även under lång tid efter
att problemen dök upp. Även andra fenomen, som stark stress, är ofta
förknippade med oupptäckt spänning i olika kroppsdelar. Man kan till och
med säga att stressupplevelsen till stor del *utgörs* av förhöjd
spänningsnivå i olika muskelgrupper.

Att spänna delar av kroppen är ofta ett sätt att undvika eller i någon
mån fly från svåra känslor i livet, exempelvis känslor av ledsenhet. Det
här gör att det kan finnas ett motstånd mot att slappna av. Nu är ett bra tillfälle att närma sig de känslorna och att
undersöka dem med nyfikenhet. Ta de
känslorna lite varsamt i handen när du fortsätter att göra det som är
viktigt för dig, utifrån din personliga målsättning. Med en generellt sänkt
spänningsnivå kan du bli flexiblare när du hamnar i svåra situationer
där autopiloten tidigare har brukat slå till.

## Del 1 i progressiv avslappning: armar, huvud & axlar (11 min)

Första gången du genomför avslappningsövningen, titta gärna på filmen så
att du utför övningarna på rätt sätt. Sedan, när du har lärt dig dem,
kan du om du vill sluta dina ögon under övningspasset. Om det känns
obehagligt att blunda, rikta i sådana fall gärna blicken mot en neutral
punkt för att ge maximal uppmärksamhet till själva övningen. Sätt dig i
en fåtölj med stöd för nacken, eller i en stol som du ställer mot en
plan yta, exempelvis en vägg. Du behöver kunna pressa nacken mot ett
underlag för att göra en av övningarna.

::: {.content-visible when-format="html"}
### Instruktioner, video

{{< video https://www.youtube.com/embed/8ygZeRNVdIU >}}

### Instruktioner, enbart ljud

<audio controls=""><source src="https://www.dropbox.com/s/66gviwf37y12ot9/KSH-06-progressiv-muskelavslappning-del-1.mp3?raw=1" type="audio/mpeg" />Din webbläsare stödjer inte uppspelning av ljudfiler.</audio>

#### Ladda ned instruktioner (mp3)

[Ladda ned en mp3-fil (7,27 MB)](https://www.dropbox.com/s/66gviwf37y12ot9/KSH-06-progressiv-muskelavslappning-del-1.mp3?dl=1){target="_blank" .bi-filetype-mp3} till din enhet.
:::

\xqr{Progressiv avslappning 1 (Youtube)}{https://youtu.be/8ygZeRNVdIU}

\xqr{Ladda ned en mp3-fil (7,27 MB) till din enhet.}{https://www.dropbox.com/s/66gviwf37y12ot9/KSH-06-progressiv-muskelavslappning-del-1.mp3?dl=1}

## Planera för träning i progressiv avslappning

Vi fortsätter med del 2 av progressiv avslappning I nästa avsnitt. Under
tiden, träna på del 1 så ofta du kan. Det tål att upprepas: Integrera
gärna träning (särskilt för muskelgrupper som du har upptäckt att du är
spänd i) i vardagen. Det går att träna på progressiv avslappning var som
helst: i duschen, på mötet, i bilen \... 

::: {.content-visible when-format="html"}
[Planera för framgång (PDF)](forms/100respekt-planera-traning.pdf){.bi-filetype-pdf}
:::

\xqrform{Planera för framgång (PDF)}{forms/100respekt-planera-traning.pdf}

Har du använt arbetsbladet ovan och tänkt till om hur du kan hjälpa dig själv att
träna progressiv avslappning? Om ja, så bra! Det kommer att hjälpa dig att gå
från ord till handling.