---
lang: sv
title: Tänkandet vid bristande självhävdelse
---

\label{sec-thinking}

Vårt sätt att tänka kan hindra oss från att hävda oss på ett
konstruktivt sätt, som vi konstaterade i vecka 1. Alla har vi antaganden
och föreställningar om oss själva, andra människor och om hur världen
fungerar. Dessa antaganden är ett resultat av de upplevelser i tillvaron
som vi har haft och är förstås helt logiska utifrån hur vi förstod
världen i de situationerna. Det kan dock hända att vi inte har
uppdaterat vårt tänkande fast vi har rört på oss och lämnat de
upplevelserna bakom oss. Kanske har vi till exempel fått lära oss av
våra familjer att vi riskerar att bli förlöjligade om vi visar att vi är
ledsna. Då är det inte så konstigt om det har resulterat i antagandet
”att uttrycka ledsenhet är dåligt, om jag gör det kommer andra att se
ned på mig”. Även om vi har blivit äldre och inte längre befinner oss i
den ursprungliga situationen kan antagandet finnas kvar. Vi fortsätter
att utgå från att våra antaganden är sanna, utan att testa
sanningshalten i dem. Ett resultat av det kan vara att vi inte uttrycker
vår ledsenhet när vi har den och istället blir stressade eller
deprimerade. Eller så uttrycker vi vår ledsenhet som ilska mot oss
själva eller andra människor.

Här är en lista med tänkande som typiskt sett inte är konstruktivt
självhävdande. Se om några av exemplen stämmer in på dig.

-   ”Jag borde inte säga vad jag verkligen känner eller tänker eftersom
    jag inte vill tynga ned andra med mina problem.”
-   ”Om jag hävdar mig själv kommer den andra personen att bli upprörd
    och det kommer förstöra vår relation.”
-   ”Det blir bara hemskt pinsamt om jag säger vad jag tänker.”
-   ”Om någon säger ’nej’ till min begäran är det för att personen inte
    tycker om mig eller älskar mig.”
-   ”Jag borde inte behöva säga vad jag behöver eller hur jag känner:
    Människor som står nära mig borde redan veta vad det är.”
-   ”Att säga vad man tycker visar att man inte bryr sig om andra, det
    är oförskämt och själviskt.”
-   ”Jag har ingen rätt att ändra mig i en fråga; det har inte andra
    heller.”
-   ”Det löser sig på något sätt ändå, och hur som helst är det inte
    mitt fel.”
-   ”Folk ska hålla sina känslor för sig själva.”
-   ”Om jag visar att jag har ångest kommer andra människor tycka att
    jag är svag och förlöjliga eller utnyttja mig.”
-   ”Om jag tar emot och accepterar en komplimang från någon betyder det
    att jag förhäver mig själv.”

## Mina egna hindrande antaganden

Ägna några minuter åt att försöka identifiera några ytterligare
hindrande antaganden som du har i relationer/situationer som du vill 
utmana dig själv i. Utgå från situationer som du tagit med i arbetsbladet 
med dina [SMARTa målsättningar](1-5.qmd)\xpageref{sec-smartgoals}, som du formulerade under vecka 1 och jobbade vidare med under vecka 2.

::: {.content-visible when-format="html"}
[Hindrande antaganden för konstruktiv självhävdelse (PDF)](forms/100respekt-hindrande-antaganden-sjalvhavdelse.pdf){.bi-filetype-pdf}
:::

\xqrform{Hindrande antaganden för konstruktiv självhävdelse (PDF)}{forms/100respekt-hindrande-antaganden-sjalvhavdelse.pdf}