---
lang: sv
title: Allas rätt att hävda sig själva
---

\label{sec-rights}

Många av idéerna som idag förknippas med träning i konstruktiv
självhävdelse kommer från *When I say no, I feel guilty: how to
cope--using the skills of systematic assertive therapy* av @smith1975say.
Boken innehåller en ”rättighetsförklaring”. Varje människa har rätt att
hävda sig själv. Här är några av rättigheterna som du och alla andra
har.

-   Du har rätt att vara domare över ditt eget beteende, dina egna
    tankar och dina egna känslor, och att ta ansvar för deras uttryck
    och konsekvenser.
-   Du har rätt att säga nej.
-   Du har rätt att inte ange några skäl eller ursäkter för ditt
    beteende.
-   Du har rätt att själv avgöra om du är ansvarig för att hitta
    lösningar på andra människors problem.
-   Du har rätt att ändra åsikt.
-   Du har rätt att ha en annan åsikt än andra personer.
-   Du har rätt att göra misstag -- och att ta ansvar för dem.
-   Du har rätt att säga ”Jag vet inte”.
-   Du har rätt att vara ologisk när du fattar beslut.
-   Du har rätt att säga ”Jag förstår inte”.
-   Du har rätt att säga ”Jag bryr mig inte”.

En viktig del av dessa **rättigheter** är att de är sammanlänkade
med **ansvar**. Den första punkten var som du såg att du har rätt till
dina egna tankar, beteenden och känslor, men också att det är du som
behöver ta ansvar för konsekvenserna av ditt tänkande och handlande.
Ibland tror människor att de hävdar sig själva konstruktivt fast de i
själva verket glömmer bort att uppmärksamma vilka konsekvenser som deras
handlande får på andra personers rättigheter. Det sättet att handla
ligger närmare en aggressiv kommunikationsstil.

## Vilka av rättigheterna ovan skriver du under på?

Är det någon eller några av rättigheterna ovan som provocerar dig?
Vilken eller vilka? Eller några som du vill skriva under på direkt?
Använd det här arbetsbladet för att ställa samman dem.

Försök också gärna komma på ytterligare några rättigheter, särskilt
sådana som balanserar de ohjälpsamma, hindrande antagandena som du skrev
upp i förra avsnittet.

::: {.content-visible when-format="html"}
[Mina rättigheter att hävda mig själv (PDF)](forms/100respekt-mina-rattigheter.pdf){.bi-filetype-pdf}
:::

\xqrform{Mina rättigheter att hävda mig själv (PDF)}{forms/100respekt-mina-rattigheter.pdf}
