---
lang: sv
title: Så funkar beteendeexperiment
tbl-colwidths: [40, 60]
---

Ibland räcker det inte med att observera och beskriva sina tankar,
känslor och beteenden. Det kan kännas som att man lär sig mycket om sig
själv men att inget i praktiken ändras. I en sådan situation är ett
beteendeexperiment mycket användbart för att aktivera sig i livet och
utvärdera hur det gick. Beteendeexperiment handlar om att utmana sina
negativa förväntningar och att bryta undvikande. 

Någon kanske till exempel har den negativa förutsägelsen ”Om jag hävdar
mig själv kommer den andra personen att bli upprörd och vår relation
kommer att bli förstörd”. För personen som tänker så har antagandet
inneburit att han eller hon alltid har gått med på vad andra
föreslagit även om det har gått helt emot vad personen egentligen har
velat göra. Förutsägelsen är så starkt att personen inte ens kan tänka
sig att hävda sina egna åsikter. Personen har kört fast.

Ett sätt att komma loss är att göra ett experiment som går ut på att
pröva giltigheten i förutsägelsen att den andra personen kommer att bli
upprörd och att relationen kommer att gå i kras. Att göra experimentet
kan vara utmanande och väcka en hel del ångest som är svår att uthärda
-- kom då ihåg att kroppen inte gör åtskillnad mellan rädsla inför
livshotande fara och ångest inför en tanke. Det är i sig inte farligt
att uppleva ångest.

Särskilt i början, när man är ovan att göra beteendeexperiment, är det
hjälpsamt att planera det så bra som möjligt. I det här programmet får
du träna på det! Det kan vara klokt att börja med ett lite enklare
experiment och gradvis gå vidare med allt mer utmanande situationer.

Det övergripande målet med hela det här självhjälpsmaterialet är att hjälpa dig att lära
dig att göra beteendeexperiment så att du kan fortsätta med det i ditt
eget liv -- hela livet ut. Det är en högst bärbar färdighet som kan dra nytta av 
var du än är i livet.

{{< video https://www.youtube.com/embed/Lepx2oU1k2E >}}

## Beteendeexperiment, steg för steg

Så här kan man lägga upp ett välplanerat beteendeexperiment, steg för
steg.

1.  Det första steget är att **identifiera förutsägelsen som du har om
    situationen** och om hur du kan avgöra om förutsägelsen stämmer. Det
    här är ett viktigt steg. Om du inte tydligt kan avgöra om det
    antagandet säger faktiskt har inträffat så är risken att du själv
    flyttar målstolparna under eller efter experimentet och inte
    upptäcker skillnaden.
2.  Du behöver också **identifiera de ej självhävdande beteenden som du
    brukar ta till** så att du kan vara säker på att du utför
    experimentet utan att göra de sakerna.
3.  Därefter fortsätter du med att **skriva ned ett antal mer positiva
    och hjälpsamma förutsägelser** (utifrån dina egna erfarenheter eller
    föreställningsförmåga) om vad som kan hända. 
4.  Sedan är det dags att **planera själva experimentet**. I det ingår
    att tydligt bestämma vilka steg som ska ingå i genomförandet. Gör
    det tydligt för dig själv när, var och hur experimentet ska gå till.
    Här identifierar du också konstruktiva självhävdande beteenden som
    du kommer att använda dig av i experimentet.
5.  När du har utfört experimentet är det läge
    att **utvärdera resultatet**. Fråga dig själv:
    -   Vad hände?
    -   Fick du stöd för dina ursprungliga negativa förutsägelser?
        -   Om ja, klarade du av att ändå göra det som var viktigt?
        -   Om nej, så bra!
    -   Vad lärde du dig av experimentet?

## Exempel på ett beteendeexperiment

Här beskriver vi ett experiment som prövar antagandet ”Om jag hävdar mig
själv kommer den andra personen att bli upprörd och vår relation kommer
att bli förstörd”.

::: {.content-visible when-format="html"}
[Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf)
:::


<!-- ### Steg 1 - Identifiera din förutsägelse -->

<!--   ---------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------- -->
<!--   Situation                                                              Om jag egentligen är upptagen ska jag säga \'nej\' nästa gång Lisa frågar om jag vill följa med och handla kläder. -->
<!--   Förutsägelse                                                           Hon kommer bli upprörd och arg och inte längre vilja vara min vän. -->
<!--   Hur mycket tror jag att det ska hända (på en skala från 0 till 100)?   70 -->
<!--   Hur vet jag om det har hänt?                                           Hon kommer lägga på luren, inte ringa upp igen om jag ringer, inte prata med mig -->
<!--   ---------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------- -->

<!-- ### Steg 2 - Identifiera hindrande beteenden -->

<!--   ---------------------------------------------------------------------------------------- ----------------------------------------------------------------------------- -->
<!--   Sådant jag brukar göra för att klara mig (t ex undvikande, flykt, säkerhetsbeteenden)?   Hitta på ursäkter, låtsades vara sjuk, undvika henne tills det är för sent. -->
<!--   ---------------------------------------------------------------------------------------- ----------------------------------------------------------------------------- -->

<!-- ### Steg 3 - Identifiera en mer realistisk förutsägelse -->

<!--   ---------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->
<!--   Påminn mig själv om en mer realistisk förutsägelse   Hon sa \'nej\' till mig förut och det var okej med mig. Hon kommer kanske bli besviken men om hon är en god vän kommer hon inte bli arg och vi kommer fortsätta vara vänner -->
<!--   ---------------------------------------------------- ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->

<!-- ### Steg 4 - Ange ditt målbeteende (från din SMARTa målsättning) -->

<!--   --------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->
<!--   Vad vill jag att göra annorlunda, för att testa de två förutsägelserna?   Istället för att undvika henne vill jag ringa upp direkt och förklara att jag har ett möte jag måste förbereda och inte kan ses på stan och shoppa. Jag vill boka in en annan tid med henne istället. -->
<!--   --------------------------------------------------------------------------- -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->

<!-- ### Steg 5 - Utför och utvärdera experimentet -->

<!--   ---------------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->
<!--   Vad hände faktiskt?                                        Hon sa att det var lugnt och faktiskt passade henne också. Vi ska ta en fika på onsdag nästa vecka. -->
<!--   Hur väl stämde min första förutsägelse?                    0 -->
<!--   Vilken förutsägelse fick stöd?                             Den mer realistiska -->
<!--   Hur var det att bete sig annorlunda från hur jag brukar?   Läskigt, svårt i början, sen lättare -->
<!--   Vad lärde jag mig av experimentet?                         Jag brukar förvänta mig det värsta och då är jag ofta passiv. Det kändes bra att vara ärlig och rak. Om jag hävdar mig själv blir andra oftast inte arga, om de ändå blir det är det deras och inte mitt problem att jobba med. -->
<!--   ---------------------------------------------------------- ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- -->
