---
lang: sv
title: "Uppgift: Fortsätt träningen i progressiv avslappning"
---

I förra modulen påbörjade du träning i progressiv avslappning. Nu när
du redan är igång får du här möjlighet att fortsätta med nästa del.

## Uppgift: Del 2 i progressiv avslappning: mage, rygg & ben (11 min)

Den här veckan fokuserar vi på andningen, magen, ryggen och benen.
Första gången du genomför avslappningsövningen, titta gärna på filmen så
att du utför övningarna på rätt sätt. Sedan, när du har lärt dig dem,
kan du om du vill sluta dina ögon under övningspasset. Om det känns
obehagligt att blunda, rikta i sådana fall gärna blicken mot en neutral
punkt för att ge maximal uppmärksamhet till själva övningen. 

::: {.content-visible when-format="html"}
### Instruktioner, video

{{< video https://www.youtube.com/embed/Sfpfa75e93k >}}

### Instruktioner, enbart ljud

<audio controls=""><source src="https://www.dropbox.com/s/7znxp4ac5m655zu/KSH-06-progressiv-muskelavslappning-del-2.mp3?raw=1" type="audio/mpeg" />Din webbläsare stödjer inte uppspelning av ljudfiler.</audio>

#### Ladda ned instruktioner (mp3)

[Ladda ned en mp3-fil](https://www.dropbox.com/s/7znxp4ac5m655zu/KSH-06-progressiv-muskelavslappning-del-2.mp3?dl=1){target="_blank"} till din mobil.
:::

Precis som i förra veckan rekommenderar vi att du tränar på del 2 så
ofta du kan. Det tål att upprepas: Integrera gärna träning (särskilt för
muskelgrupper som du har upptäckt att du är spänd i) i vardagen. Det går
att träna på progressiv avslappning var som helst: i duschen, på mötet,
i bilen \...

Är det motigt att komma igång? Påminn dig om det du skrev ned i formuläret i förra modulen -- och om du inte gjorde det då, får du här en ny chans:

::: {.content-visible when-format="html"}
[Planera för framgång (PDF)](forms/400ac1a33963196edb6d50c4871b2e3d.pdf)
:::