---
title: "Uppgift: Utvärdera träningen i avslappning"
---

I förra modulen smygstartade du träning i progressiv avslappning. Nu när
du redan är igång får du här möjlighet att fortsätta med nästa del.

##e99da346c70816c52c235c950f2ad396=

## Uppgift: Del 2 i progressiv avslappning: mage, rygg & ben (11 min)

Den här veckan fokuserar vi på andningen, magen, ryggen och benen.
Första gången du genomför avslappningsövningen, titta gärna på filmen så
att du utför övningarna på rätt sätt. Sedan, när du har lärt dig dem,
kan du om du vill sluta dina ögon under övningspasset. Om det känns
obehagligt att blunda, rikta i sådana fall gärna blicken mot en neutral
punkt för att ge maximal uppmärksamhet till själva övningen. 

 Du kan också använda en mp3-fil med ljudspåret från filmen ovan, som du
kan lyssna på direkt eller [ladda ned
direkt](https://www.dropbox.com/s/7znxp4ac5m655zu/KSH-06-progressiv-muskelavslappning-del-2.mp3?dl=1){target="_blank"}
till din mobil.

Your browser does not support the audio element.

Precis som i förra veckan rekommenderar vi att du tränar på del 2 så
ofta du kan. Det tål att upprepas: Integrera gärna träning (särskilt för
muskelgrupper som du har upptäckt att du är spänd i) i vardagen. Det går
att träna på progressiv avslappning var som helst: i duschen, på mötet,
i bilen \...
