---
lang: sv
title: Fler tekniker för konstruktiv självhävdelse
---

## Empatisk självhävdelse

Empatisk självhävdelse betyder att vi hävdar oss själva samtidigt som vi
försöker förstå en annan persons känslor, behov eller önskemål. Den här
typen av konstruktiv självhävdelse kombinerar alltså att vi säger vad vi
själva behöver och vill med ett empatiskt erkännande av den andra
personen.

Empatiskt självhävdande kan användas när du är inblandad i en situation
som inte stämmer överens med dina behov. Samtidigt som du säger vad du
tänker eller känner visar du att du är lyhörd för hur den andra personen
har det.

Exempel på empatisk självhävdelse:

-   ”Jag förstår att du inte gillar det nya arbetssättet. Tills vi kan
    ändra det igen vill jag ändå att du gör på det nya sättet.”
-   ”Jag vet att du är upptagen nu, Johan, men jag skulle vilja be dig
    om en sak.”
-   ”Jag har full förståelse för att det är svårt att säga exakt vad
    priset kommer att bli, jag skulle ändå behöva en uppskattning,
    mellan tummen och pekfingret.”

Empatisk självhävdelse kan hjälpa dig att hålla igen från att
överreagera på ett aggressivt sätt. Med empatisk självhävdelse ger du
dig själv lite betänketid, för att bättre förstå i vilken sits den andra
personen befinner sig.

Det är möjligt att överanvända vissa empatiskt självhävdande fraser. Då
kan det börja låta som att du inte är uppriktig. I exemplet ”Jo, jag
förstår dina känslor, men ...”, så vattnas den empatiska delen ”jag
förstår dina känslor” ut av det följande ordet ”men”. Frasen ser ut som
konstruktiv självhävdelse men blir istället ett uttryck för
aggressivitet.

## Konsekvensbaserad självhävdelse

Det här är den starkaste sortens självhävdelse och är ett beteende som
används som sista utväg. Det används vanligtvis i en situation när någon
inte har respekterat andras rättigheter och du vill påtala detta utan
att själv bli aggressiv. I en jobb-situation kan det användas när
överenskomna arbetssätt eller riktlinjer inte följs.

Konsekvensbaserad självhävdelse går ut på att informera personen om
konsekvenserna om hen inte ändrar sitt beteende. Det kan väldigt lätt
uppfattas som hotande och därför aggressivt. Använd bara det här sättet
att hävda dig själv när du har sanktioner (konsekvenser) som du kan ta
till, och bara om du också är beredd att göra det.

Eftersom den här typen av självhävdelse lätt kan uppfattas som
aggressivitet behöver du vara mycket försiktig med de icke-verbala
signaler som du sänder. Håll rösten låg och i en jämn nivå och volym, ha
god ögonkontakt och försök att hålla kroppen och ansiktet avslappnade.

Exempel på konsekvensbaserad självhävdelse:

-   ”Om du fortsätter att undanhålla mig information har jag inget annat
    val än att ta detta till produktionschefen. Jag skulle helst slippa
    det.”
-   ”Johan, jag är inte beredd på att låta mina medarbetare samarbeta
    med dina i projektet såvida du inte ger dem tillgång till samma
    lokaler och utrustning som dina medarbetare har.”
-   ”Om det här händer igen har jag inget annat val än att dra igång ett
    formellt disciplinärende. Jag skulle föredra att inte göra det.”

## Diskrepansbaserad självhävdelse

Diskrepansbaserad självhävdelse går ut på att peka på skillnaden mellan
vad som tidigare överenskommits och vad som faktiskt händer. Det är
användbart för att bringa klarhet i om det finns någon motsättning i
åsikt eller om det föreligger ett missförstånd, när ord och beteende
inte stämmer överens för en person.

Två exempel på självhävdande i situationer med skillnad i ord och
handling:

-   ”Som jag förstod det kom vi överens om att projekt A hade högsta
    prioritet. Nu ber du om mer tid för projekt B. Jag skulle vilja få
    klarhet i vilket projekt som just nu är viktigast.”
-   ”Paul, å ena sidan säger du att du vill förbättra samarbetet mellan
    avdelningarna, men å andra sidan säger du saker om oss som gör det
    svårt för oss att samarbeta. Jag håller med om att vi kan förbättra
    situationen, så jag skulle vilja prata om det.”

## Självhävdelse vid negativa känslor

När du är sårad i en relation, eller känner starka negativa känslor
gentemot en annan person -- som ilska eller förakt -- kan du använda dig
av följande självhävdande teknik: På ett kontrollerat och lugnt sätt
uppmärksammar du personen om vilka oönskade effekter den andras beteende
har på dig. Det ger dig möjlighet att hantera de jobbiga känslorna, utan
att tappa humöret på ett okontrollerat sätt. Och det ger den andra
personen möjlighet att förstå på vilket sätt hans eller hennes handlande
påverkar dig.

Här är två exempel på självhävdelse vid negativa känslor:

-   ”När du kommer hem sent, utan att säga till om det innan, oroar jag
    mig för att något är fel och då blir jag arg. Jag skulle verkligen
    uppskatta om du kunde slå en signal och säga till innan.”
-   ”Varje gång du avbryter mig när jag jobbar med balansräkningen måste
    jag börja om igen. Jag känner mig irriterad över det, så jag skulle
    föredra att du väntade tills jag är klar.”
