---
lang: sv
title: Repig grammofonskiva-teknik för att säga ”nej”
---

Små barn är experter på den här tekniken, med vilken du upprepar din
ståndpunkt som en repig gammal grammofonskiva av vinyl, som hakat upp
sig. Den här färdigheten går ut på att först komma på vad du ska säga,
och sedan repetera det så många gånger som det behövs, på ett lugnt och
avslappnat sätt. Den här färdigheten är användbar i de flesta
situationer. Det är en bra teknik att använda när du har att göra med
smarta, vältaliga personer, eftersom det enda du måste göra är att hålla
dig till det du vill säga. Tekniken hjälper dig att behålla lugnet
eftersom du inte behöver tänka på vad du ska säga för att inte falla i
irrelevanta logiska fällor; du behöver bara hålla rak kurs mot ditt mål.
Tekniken är särskilt bra i situationer när du vill säga 'nej' (vi går in
på det här mer i detalj i modul 6).

## Exempel på repig grammofonskiva-tekniken

Karin

:   -- Kan jag låna 200 kronor av dig?

David

:   -- Jag kan inte låna ut några pengar, jag är luspank.

Karin

:   -- Jag betalar tillbaka så fort jag kan. Jag är desperat! Kom igen,
    var en kompis!

David

:   -- Jag kan inte låna ut några pengar.

Karin

:   -- Om det var jag skulle jag göra det. Du kommer inte sakna 200
    kronor.

David

:   -- Jag är din kompis men jag kan inte låna dig pengar, jag är pank.

Repig grammofonskiva-tekniken kan kombineras med övriga tekniker för
konstruktiv självhävdelse som du har lärt dig. Börja alltid med den
mildaste hållningen, och bygg på utifrån vad du bedömer är nödvändigt
i situationen. Undvik att direkt gå på den starkaste konsekvensen,
eftersom det kan uppfattas som ett hot och som aggressivt beteende,
snarare än konstruktiv självhävdelse.

Det följande exemplet av repig grammofonskiva-tekniken använder alla
nivåerna av självhävdelse, från grundläggande, via empatisk till
konsekvensbaserad självhävdelse.

### Grundläggande

Kunden

:   -- Jag köpte den här klockan igår. Vredet för att ställa om tiden
    fungerar inte som det ska, så jag vill byta den.

    Här kan expediten gå med på ditt önskemål eller kanske säga:

Expediten

:   -- Du skulle ha kontrollerat klockan innan du lämnade affären.

### Empatisk

Kunden

:   -- Jag förstår att det skulle ha gjort saken lättare för dig, men
    jag vill ända byta ut den.

    Här kan expediten gå med på ditt önskemål eller säga något i stil
    med:

Expediten

:   -- Jag har inte mandat att byta ut varor.

Kunden

:   -- Jag vill ändå få den utbytt.

    Efter en stunds ordväxling kan nivån höjas till konsekvensen.

### Konsekvens

Kunden

:   -- Jag vill få klockan utbytt. Om du inte är beredd att byta den
    kommer jag ta upp det med huvudkontoret. Jag skulle föredra att lösa
    problemet nu.

En nackdel med den här tekniken kan uppstå när personen du pratar med
helt enkelt vägrar göra det du ber om. När hen fortsätter att motstå din
begäran riskerar den att förlora i kraft, varje gång du upp upprepar
den. Om du upprepar din begäran för ofta kan det slå tillbaka på
auktoriteten bakom dina ord. I sådana situationer är det nödvändigt att
ha några konsekvenser till hands.
