---
lang: sv
title: "Övning: Mängdträna -- övning ger färdighet"
---

Färdighet i dessa tekniker kräver övning -- ingen lär sig spela piano
utan att traggla. Genom att traggla lär sig synen, tanken och fingrarna
att samarbeta och till slut kan man spela riktigt fint. Börja med
grundläggande självhävdelse och öva på det en gång under veckan som
kommer innan du går vidare med övriga tekniker. Tillämpa den valda
självhävdelsetekniken i en lämplig situation med hjälp av ett
beteendexperiment.

## Mängdträna med omväxlande svårighetsgrad

När du övar på dessa tekniker: Planera, genomför och dokumentera dem som
beteendexeperiment. Utgå från din första SMARTa målsättning eller välj
en ny situation som du vill träna i. Genomför ditt beteendeexperiment på
precis samma sätt som det du har genomfört tidigare i när du jobbat med det här självhjälpsmaterialet, men se om du kan lägga till någon av teknikerna från
det här avsnittet. Det kommer att kännas ovant och konstlat till en
början, men genom att pröva teknikerna och sedan utvärdera utfallen kan
du hitta de sätt som ger dig framkomlighet för dig.

Sikta på att utföra åtminstone två (2) olika beteendeexperiment den här
veckan. Ju fler tillfällen du tränar, desto bättre! Om du tidigare har
genomfört ett svårt beteendeexperiment, gör då gärna ett litet lättare
härnäst. Du förtjänar att också få bokföra lite enklare vunna
framgångar.

::: {.content-visible when-format="html"}
[Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf)
:::
\xqrform{Planera och genomför ett beteendeexperiment (PDF)}{forms/100respekt-beteendeexperiment.pdf}

Titta gärna genom exempel-arbetsbladet nedan för vägledning, när du planerar, utför och utvärderar ditt eget experiment.

::: {.content-visible when-format="html"}
[Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf) 
:::
\xqrform{Exempel: Planera och genomför ett beteendeexperiment (PDF)}{forms/100respekt-exempel-beteendeexperiment.pdf}
