---
title: "Uppgift: Korta ned progressiv avslappning"
---

Kommer du ihåg att *progressiv* betyder \"gradvis framåtskridande\"?
Tanken med träning i progressiv avslappning är att du ska få möjlighet
att bli allt bättre på att märka när du är spänd och att sänka
spänningsgraden i stunden.

Du som redan har tränat progressiv avslappning del 1 och 2, växla gärna
över till den här korta versionen nu! Du som inte har kommit igång med
del 1 och 2, gör gärna den här korta versionen \"varvat\" med de mer
grundläggande avslappningsövningarna (från de tidigare modulerna) under
veckan som kommer.

## Kort version av progressiv avslappning

Du kan lyssna på filen direkt eller ladda ned den som mp3-fil [direkt
till din
mobil](https://www.dropbox.com/s/wa55oouszt68ikh/KSH-06-progressiv-muskelavslappning-kort.mp3?dl=1){target="_blank"}.

Your browser does not support the audio element.

## Träna snabbavslappning i vardagen

Testa också att i din vardag gå vidare till ytterligare en nivå --
snabbavslappning. Med den här metoden kan du i vardagen skanna av var du
är spänd och slappna av på bara några sekunder!

Precis där du är i stunden, känn efter i kroppen var du är spänd. Spänn
den muskelgruppen helt kort och slappna sedan av i den. Ta sedan ett
djup andetag och när du andas ut tänker du \"Slappna av\" (eller någon
annan självinstruktion som känns bra för dig). 

Övning: Skanna genom kroppen precis just nu, när du läser det här. Är du
spänd någonstans? Slappna av i de musklerna (spänn dem först om det
underlättar). Ta ett djupt andetag med magen, andas ut långsamt, säg
\"Slappna av\" till dig själv. 
