---
lang: sv
title: "Övning: Identifiera fysisk spänning just nu"
---

När vi kommunicerar på ett passivt eller aggressivt sätt har vi ofta
ångest eller är arga, och det återspeglas i våra kroppar: Vi kan bli
spända i axlarna, nacken, käken eller i hela kroppen. Med tiden kan
spänningen i kroppen öka till en punkt då vi får huvudvärk, ryggskott
eller magproblem -- faktiskt en hel rad olika fysiska problem. Det blir
också allt svårare att slappna av.

{{< video https://www.youtube.com/embed/32GSfdwprHU >}}

För att kommunicera på ett sätt där vi hävdar oss själva konstruktivt
behöver vi dämpa graden av aktivering i kroppen, liksom spänningsgraden
som vi kan erfara när vi hamnar i ”heta” situationer eller lägen där
vi känner oss obekväma.

Det första steget för att reducera fysisk spänning är att identifiera
var du är spänd i kroppen. Se om du kan upptäcka några mönster av spända områden. Är du mest spänd
i magen och ländryggen (nedre delen av ryggen), i dina armar och ben,
eller runt nacken och axlarna?

Här och precis nu, skanna av graden av spänning i kroppen. Använd listan ovan och låt din uppmärksamhet vila vid varje punkt tills du lägger märke till om du är spänd eller avslappnad -- gå då vidare till nästa punkt.

- Huvudsvålen (skalpen)
- Pannan
- Kring ögonen
- Tinningarna
- Käken
- Nacken
- Axlarna
- Bröstet
- Överarmarna
- Underarmarna
- Händerna
- Magen
- Ländryggen (svanken)
- Rumpan
- Låren
- Vaderna
- Fötterna

Du kan upprepa övningen flera gånger. Testa dig gärna
igen när du är i en mer stressande situation för att se om du då är
spänd i samma eller andra kroppsdelar. Upptäcker du någon skillnad?
