---
lang: sv
title: "Övning: Hitta dina egna sätt att sänka spänningsnivån"
---

När människor börjar uppmärksamma sina kroppar blir de ofta förvånade
över hur spända de verkligen är. Den goda nyheten är att det finns flera
avslappningstekniker som du kan använda för att sänka den fysiska
spänningsnivån i kroppen. Precis som med alla färdigheter som du vill lära dig och göra till nya vanor gäller att ju mer du tränar på dem, desto större inverkan kommer de ha på ditt välmående. Obehaget du eventuellt känner när du tränar är ett kvitt på att du är på väg framåt.

Här är några av alla metoder för att sänka spänningsnivån i kroppen:

-   Träning (det som passar dig -- löpning, simning, ridning, gym \...)
-   Massage
-   Progressiv muskelavslappning
-   Yoga
-   Meditation
-   Promenader i naturen
-   Musik
-   Andningsövningar
-   Tai chi

I det här avsnittet finns flera olika metoder för avslappning med. Ge dig
tid att pröva på och utforska olika sätt att slappna av den här veckan.
Det finns även gott om videor på internet, appar för smartphones och
färdiga ljudfiler att hitta för den som är intresserad.

## Vad gör dig avslappnad?

Vilka aktiviteter hjälper dig att sänka spänningsnivån i kroppen? Skriv
upp dem här nedan. Det kan till exempel vara tekniker som vi tagit upp
här ovan eller andra personliga avslappningsfavoriter. 

::: {.content-visible when-format="html"}
[Mina sätt att sänka spänningsnivån (PDF)](forms/100respekt-avslappningstekniker.pdf)
:::
\xqrform{Mina sätt att sänka spänningsnivån (PDF)}{forms/100respekt-avslappningstekniker.pdf}

I återstoden av avsnittet kommer vi introducera några tekniker som du
kanske eller kanske inte har hört talas om förut.