---
lang: sv
title: "Uppgift: Bli din egen avslappningsguru"
---

Med progressiv avslappning arbetar du dig genom varje muskelgrupp i
ordning. Om vi har gått omkring och varit spända en längre tid och sedan
försöker slappna av, kan det vara svårt att lyckas. Pröva själv, så får
du se: Försök att genast slappna av i axlarna! De flesta tycker att det
är väldigt svårt att bli riktigt avslappnade på kommando.

## Skapa din egen version av progressiv avslappning

I modul 2 fick du träna på [progressiv avslappning del
1](2-5.qmd),
i modul 3 på [progressiv avslappning del
2](3-5.qmd)
och i modul 4 på en [kort variant av progressiv
avslappning](4-5.qmd).
Där fick du också hjälp av förinspelade ljudfiler och videofilmer som
visade hur de olika momenten går till. Fortsätt gärna med dem!

Men skapa också gärna en *egen personligt anpassad inspelning* av
instruktionen för progressiv avslappning, exempelvis med hjälp av din
mobiltelefon. Eller gör avslappningsproceduren ur minnet och använd bara
textmanuset nedan som stöd (det spelar ingen roll om du kastar om
ordningen). Oavsett hur du gör övningarna självständigt så får du \...

1.  En helt personligt anpassad variant i det tempo (och med det
    röstläge) som passar precis just dig.
2.  Möjlighet att göra ett urval av de övningar som är viktigast för
    dig, med fokus på de muskelgrupper du har upptäckt att du ofta är
    spänd i.
3.  Ännu bättre inlärning. Det finns inget bättre sätt att lära sig
    något än att göra det själv.

Och viktigast av allt: När du läser in din egen inspelning blir du *din
egen avslappningsguru*! Övningarna du har gjort under tidigare moduler
har en nackdel -- du riskerar att lära dig att bero av ljudfilerna och
videofilmerna för att kunna slappna av. Målet med det här
självhjälpsmaterialet är att du ska kunna använda färdigheterna som du tränar på spontant och utan hjälpmedel.

Texten nedan är inte exakt densamma som den vi har läst in på
ljudfilerna. Det gör inget alls. Du kan själv anpassa och justera texten
så att den passar precis just dig. Det viktiga är (som med det mesta i
livet) inte att det blir perfekt -- det viktiga är att du hittar det som fungerar.

## Repetition: så funkar progressiv muskelavslappning

Progressiv avslappning fungerar lite annorlunda än vanliga
avslappningsövningar: Först spänner du muskelgrupperna, sedan slappnar
du av i dem. Genom att först spänna muskeln lär du dig att ta kontroll
över den och känna igen hur det känns att vara spänd.

Försök att spänna dina axlar: Lyft dina axlar så högt du kan, som om du
ville nå dina öronspetsar med dem. Håll axlarna så i 10 sekunder. Låt
sedan axlarna sjunka ned och upplev känslan av avslappning. Med
progressiv avslappning gör du på samma sätt med var och en av de stora
muskelgrupperna -- först spänner du dem, sedan slappnar du av.

Följ varje steg nedan för var och en av muskelgrupperna. När du går
genom dem, upprepa samma mönster av spänning och avslappning. Spänn
muskelgruppen i 10 sekunder. Släpp sedan spänningen och vänta i 20
sekunder innan du spänner samma muskelgrupp igen. Lägg märke till hur
avslappningen känns! Det är viktigt att du slappnar av i en muskelgrupp
minst dubbelt så länge som du spänner den. Poängen med den här övningen
är inte spänningen utan avslappningen. Lägg noga märke till hur den
känns jämfört med spänningen.

Du kanske märker att du andas in när du spänner musklerna och andas ut
när du slappnar av. Det är den naturliga rytmen i kroppen och det är
enklast att bara följa med i den andningsrytmen. Andas in när du spänner
musklerna, andas ut när du slappnar av.

Om du vill kan du göra en inspelning av dig själv med mobiltelefonen när
du ger instruktionerna för de olika muskelgrupperna, så behöver du inte
hålla ett öga på texten när du gör övningen.

::: {.callout-tip}
## Manus för progressiv avslappning

Till att börja med, sätt dig bekvämt i en stol. Det är bättre att göra
övningarna sittandes än liggandes, så att du inte råkar somna. Hela övningen bör
ta cirka 15 till 20 minuter. Sätt båda fötterna på golvet och låt händerna vila
i knät. Låt dina ögonlock falla ned så att dina ögon sluts lätt. Lägg märke till
tyngden av din kropp, ditt huvud, dina axlar, dina armar och dina ben.
**Observera! Under övningen, se till att du slappnar av dubbelt så länge som du
spänner dig.**

1.  Knyt höger hand, och lägg märke till spänningen medan du gör det.
    Kläm åt lite hårdare och känn spänningen i näven, handleden och
    underarmen. Släpp taget och låt din hand slappna av. Notera
    skillnaden i spänning och hur avslappningen känns. Upprepa detta med
    höger hand en gång. Upprepa sedan allt igen, med vänster hand. Spänn
    och slappna sedan av i båda händerna samtidigt.
2.  Gå vidare till underarmen, genom att böja din hand framåt och nedåt.
    Låt sedan musklerna slappna av genom att räta upp handleden igen.
    Lägg märke till hur avslappningen känns. Upprepa med den andra
    underarmen.
3.  Spänn dina båda biceps-muskler genom att pressa underarmarna upp mot
    dem. Spänn dem så hårt du kan. Känn spänningen. Slappna sedan av
    genom att räta ut armarna. Lägg märke till hur avslappningen känns.
    Repetera.
4.  Flytta uppmärksamheten till axlarna. Spänn dina axlar genom att
    lyfta upp dem, som om du försökte nudda öronen med dem. Slappna
    sedan av genom att låta dem sjunka ned igen, uppmärksamma
    avslappningen. Upprepa en gång.
5.  Med armarna hängande utmed sidorna, tryck axlarna framåt. Håll så i
    10 sekunder och slappna sedan av genom att låta axlarna gå tillbaka
    till sitt naturliga läge. Lägg märke till hur avslappningen känns.
6.  Låt uppmärksamheten gå till din nacke. Om du har ont i nacken eller
    har dragit på dig en nackskada, fråga först din läkare eller
    fysioterapeut innan du gör den här övningen. Luta försiktigt huvudet
    till vänster tills dess att du känner att musklerna på höger sida av
    nacken spänns. Rulla sakta huvudet framåt och till höger, och sedan
    sakta igen tillbaka till vänster. Den här övningen ska inte göra
    ont. Om du känner smärta sträcker du musklerna för mycket, då
    behöver du ta det lite försiktigare. Upprepa en gång.
7.  Flytta uppmärksamheten till huvudet. Gör pannan så rynkig som det
    går. Det kan hjälpa att lyfta på ögonbrynen. Håll så i 10 sekunder,
    och slappna sedan av. Lägg märke till avslappningen.
8.  Slut dina ögon hårt och håll spänningen i 10 sekunder. Slappna av
    och känn hur det känns. Upprepa en gång.
9.  Bit samman käkarna i 10 sekunder. Släpp det hårda bettet och låt
    käkmusklerna slappna av. När du slappnar av helt i käken är dina
    läppar något särade. Lägg noga märke till skillnaden mellan
    muskelspänning och -avslappning. Upprepa en gång.
10. Pressa tungan hårt mot gommen. Slappna sedan av och låt tungan falla
    ned igen. Upprepa.
11. Pressa samman läpparna och forma dem till ett ”O”. Slappna sedan av
    i läpparna. Repetera. Se till att resten av ansiktet fortfarande är
    avslappnat.
12. Flytta uppmärksamheten till bröstet. Andas in och fyll dina lungor
    helt samtidigt som du spänner bröstmusklerna. Håll andan i 10
    sekunder innan du andas ut helt och låter musklerna slappna av. Töm
    lungorna helt innan du tar nästa andetag. Lägg märke till hur
    avslappningen känns. Repetera en gång.
13. Gå vidare till magen. Spänn magmusklerna och håll. Lägg märke till
    hur spänningen känns och slappna sedan av. Placera din hand på
    magen. Andas in djupt, med magen, så att handen på magen rör sig
    framåt när du andas in. Håll och slappna sedan av. Upprepa en gång.
14. Forma ryggen till en båge. Känn spänningen i ländryggen, den nedre
    delen av ryggen. Håll och slappna sedan av, och räta på dig till
    sittande ställningen igen. Upprepa en gång.
15. Spänn skinkorna i rumpan genom att pressa ihop dem. När du gör det
    ska du komma lite högre upp i stolen. Håll och slappna sedan av.
    Lägg märke till hur avslappningen känns. Upprepa en gång.
16. Fortsätt genom att flytta uppmärksamheten till benen. Spänn låren
    genom att trycka ned hälarna i golvet, så hårt du kan. Håll och
    slappna sedan av. Upprepa en gång.
17. Spänn dina vader genom att lyfta tårna upp mot smalbenet. Håll och
    slappna sedan av. Upprepa en gång.
18. Spänn dina fötter genom att rulla in tårna mot golvet. Håll och
    slappna sedan av. Lägg märke till hur avslappningen känns. Upprepa
    en gång.

När du har gått genom alla muskelgrupper är det en god idé att sitta
still några minuter för att verkligen känna hur det känns att vara
avslappnad. Res inte på dig för snabbt, eftersom det kan göra att du
återgår till det spända läget. När du slappnar av sjunker dessutom ditt
blodtryck, så om du reser dig för snabbt kan du bli lite yr.
:::

::: {.content-visible when-format="html"}
[Manus för progressiv avslappning (PDF)](forms/manus-progressiv-avslappning.pdf)
:::