---
title: "Uppgift: slappna av snabbt i \"heta\" situationer"
---

Ju mer du tränar på progressiv avslappning, desto bättre kommer du bli
på att hitta de delar av kroppen som är spända även i vardagslivet.
Ibland hamnar du i situationer som inte har utrymme för 15 till 20
minuters avslappningsövning. För de tillfällena kan du modifiera
övningen genom att välja endast de muskelgrupper som du känner är
spända, och göra de motsvarande avslappningsövningarna.

## Snabbavslappning 1

Ett av de två målen träning i progressiv avslappning är att ge dig
förmågan att märka var du är spänd och direkt slappna av, även när du är
i besvärliga situationer. (Det andra målet är allmänt sänkt
spänningsnivå, som kommer av ihållande träning i sig.)

Gör så här: Skanna genom kroppen precis just nu, när du läser det här.
Är du spänd någonstans? Slappna av i de musklerna (spänn dem först om
det underlättar). Ta ett djupt andetag med magen, andas ut långsamt, säg
\"Slappna av\" tyst till dig själv. 

##240cfc5999707bdd2883ac94b20218e9=

## Snabbavslappning 2 (stående)

Du kan också testa den här snabba avslappningsövningen, som är perfekt
att göra då och då när du arbetar vid kontorsdatorn -- kanske kan du
göra den nästa gång du får ett besvärligt mejl som får pulsen att stiga?

1.  Ställ dig upp.
2.  Andas långsamt med magen, med käken avslappnad och läpparna lätt
    isär.
3.  Andas in i 2 sekunder, andas ut i 3 sekunder. Lägg märke till din
    andning under hela övningen. Håll andningen långsam och djup.
4.  Sätt ett av dina ben framför det andra, med båda fötterna stadigt på
    underlaget. Pressa det bakre benet framåt och det främre benen
    bakåt, så att det uppstår spänning i båda benen.
5.  Sätt samman händerna bakom ryggen, och vrid dem så att handflatorna
    i de knäppta händerna är riktade mot golvet.
6.  Håll dina händer samman på det sättet, med raka armar, och
    lyft försiktigt armarna bakom ryggen upp mot huvudet.
7.  Lägg märke till hur spänningen ökar i alla dina muskelgrupper. Håll
    i 5 sekunder.
8.  Sätt dina fötter som vanligt, bredvid varandra, och låt armarna
    hänga utmed sidorna. Ta två eller tre andetag och låt spänningen
    släppa i hela kroppen.
9.  Upprepa steg 4--8 tills du känner dig helt avslappnad.

Kom ihåg att målet med alla dessa avslappningsövningar är dubbelt: både
att sänka den allmänna spänningsnivån och att lära dig känna igen
spänning i kroppen mycket snabbare än förut, så att du medvetet kan
slappna av i de spända muskelgrupperna och bli mer medvetet närvande och
därmed mer flexibel i tuffa situationer. Då blir det lättare att välja
beteenden för konstruktiv självhävdelse istället för passiv eller
aggressiv självhävdelse. Därför är det bra att träna avslappning på så
många platser som möjligt, vid så många tidpunkter som möjligt och på så
många olika sätt som möjligt.
