---
lang: sv
title: Ännu fler metoder för avslappning och medveten närvaro
---

Du har säkert hört människor prata om vikten av att kunna vara medvetet
närvarande i nuet. Medveten närvaro är inte detsamma som avslappning.
Man kan vara helt medvetet närvarande även när man har en
stressreaktion, även om det är mycket svårare än när man är avslappnad.
Att vara medvetet närvarande handlar om att ta in och uppleva det som
händer precis just nu, utan att värdera eller döma det. Det är en
färdighet som är extremt hjälpsam -- rent av en förutsättning, faktiskt
-- för att klara av att ”ta sin ångest i handen” och göra det som är
viktigt i stunden. 

På den här sidan finns några fler sätt att träna medveten närvaro och
avslappning. Vi hoppas de här tipsen kan inspirera dig att söka efter
fler sätt till sänkt spänningsnivå i vardagen. Avspänning ger dig tid
för medvetna val i livet, vilket i sin tur minskar stressen och ger dig
energi att hävda dig själv konstruktivt. Se följande förslag som ett
smörgåsbord av möjligheter. Du behöver inte tycka om allt som erbjuds på
smörgåsbordet -- men provar du dig nyfiket fram kan du mycket väl hitta
en ny favorit.

## Medveten närvaro

Träning i medveten närvaro handlar om att ta in hela situationen,
inklusive alla de dömande tankar och känslor som kommer och går (som
tankar och känslor alltid gör). Om du är extremt stressad inför en
presentation på jobbet, skulle medveten närvaro kunna handla om att
uppmärksamma att du är väldigt nervös och tänker dömande tankar som
”jag kommer aldrig klara det”. Och att sedan ändå fortsätta med det
som är viktigt, men utan att försöka trycka bort den negativa tanken
eller känslan. Det är lite som att säga ”Hej! Där är visst du igen!”
till den dömande tanken, utan att för den skull *köpa* det den dömande
tanken säger.

Som med allt annat är det vettigt att börja träna på att praktisera medveten närvaro
långt innan du hamnar i en skarp situation. Det fungerar ungefär som när du tränar på gymmet. Själva hanteln är ett verktyg som hjälper dig att få starkare muskler. De flesta tränar inte muskelstyrka för att kunna bära omkring på hantlar, utanför att få ett bättre vardagsliv, om det så handlar om att vara nöjd med sin figur på stranden eller att klara av att bära hem matkassar från affären. Tänk på guidade övningar i medveten närvaro som hantlar eller andra redskap: De är i sig tämligen meningslösa, men hjälper dig att öva upp faktiskt mental styrka som du senare kan använda för att tänka och handla mer flexibelt i verkliga livet -- inklusive i skarpa situationer.

Här är en portabel övning (som du
kan såväl stående som gående) på Spotify från psykologen Fredrik
Livheim.

::: {.content-visible when-format="html"}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/3dRaQwCRT2Nb2ASCa3L6pa?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
:::

Här är ytterligare några medveten närvaro-övningar som du kan prova, från Stressmottagningen. 

::: {.content-visible when-format="html"}
{{< video https://www.youtube.com/embed/gGi03lwf_bw >}}

{{< video https://www.youtube.com/embed/4kVAHhJted8 >}}
:::

## Lugn, kontrollerad andning

::: {.callout-tip}
## Boktips för dig med panikångest
Om du lider av panikångest är lugn och kontrollerad
andning en särskilt viktig teknik för att inte hyperventilera
(överandas). Andningsövningar för panik är till och med ännu långsammare
än i den här övningen. Om du har panikattacker, titta närmare på
självhjälpsboken [*Ingen panik: Fri från panik- och ångestattacker i
10 steg med kognitiv
beteendeterapi*](http://libris.kb.se/bib/12089987) av Carlbring och
Hanell (2013). Du kan läsa och göra övningarna i den på egen hand, eller
ta hjälp av en KBT-psykolog eller -psykoterapeut.
:::

Sätt dig
bekvämt utan korsade armar eller ben, med båda fötterna på golvet och
händerna mjukt vilande i knät. Om du föredrar att sluta ögonen under den
här övningen kan du göra det.

1.  Använd näsan istället för munnen när du andas. Börja med att bara
    observera din andning. Lägg märke till hur det känns att andas in.
    Och hur det känns att andas ut.
2.  Försök att sakta ned på andningstakten genom att mjukt och stadigt
    dra in luft ned mot magtrakten. Pausa helt kort innan du lägger
    märke till hur den långsamma och stadiga utandningen känns.
3.  När du är uppmärksam på din andning kan du börja hitta en rytm där
    du räknar till tre sekunders inandning och två sekunders utandning.
    Det ger en andningstakt på 10 andetag i minuten. (En normal
    andningstakt är 10--14 andetag i minuten.)
4.  Försök behålla här långsamma, jämna och kontrollerade rytmen på din
    andning genom att räkna tyst för dig själv i huvudet. Skynda inte på
    när du räknar.
5.  Fortsätt andas med den här rytmen i 10 till 15 minuter. När du är
    klar, öppna ögonen och låt det gå en liten stund innan du lämnar
    stolen.

## Världens mest avslappnande låt?

Enligt en
[rapport](https://www.britishacademyofsoundtherapy.com/wp-content/uploads/2019/10/Mindlab-Report-Weightless-Radox-Spa.pdf){target=”_blank”}
från 2011 är *Weightlessness* från Marconi Union ”världens mest
avslappnande låt”. Det tvärsäkra påståendet ska förstås tas med en nypa salt,
men låten är utformad för att sänka
pulsen på lyssnaren, genom gradvis sänkning av tempot från 60 slag i minuten (*beats per minute*, bpm) i början av låten
till 50 bpm i slutet. Eftersom den inte har någon uppmärksamhetsfångande
melodi att tala om samt att den är ganska lång, ger dig dig tid att
varva ned. Den sägs i genomsnitt lugna pulsen med 35% -- och dessutom
lindra ångest. Prova själv -- vad tycker du?

::: {.content-visible when-format="html"}
{{< video https://www.youtube.com/embed/UfcAVejslrU >}}
:::

Du kanske också har några egna favoritlåtar för att komma ned i varv?

## Riktad visualisering

Med tekniken visualisering använder du din egen fantasi för att sänka
stressnivån. Pröva gärna en av alla ljudinspelningar och appar med
guider för visualisering. Det gäller att du utforskar tills du hittar en
övning som passar och är till hjälp för just dig. Vägledd visualisering
praktiseras och forskas i på cancer- och smärtkliniker runt om i
världen. Visualisering är effektiv i behandling av många
stressrelaterade symtom som huvudvärk, muskelkramper, kronisk smärta och
ångest. Ibland kan effekterna kännas direkt och ibland tar det flera
veckor av övningar innan en förbättring kommer.

Visualisering går ut på att föreställa sig en scen eller en bild så
fullständigt som du kan. Ibland använder människor visualisering för att
sätta mål. Till exempel kan idrottsutövare använda visualisering som en
del av träningen. De kan föreställa sig ett lopp eller en tävling som de
ska delta i, in i minsta detalj: De ser sig själva i loppet och
föreställer sig allt de kommer att se, smaka, höra och lukta. De
fantiserar om de svåra delarna av loppet och hur de kommer att klara av
dem. De känner utmattningen och föreställer sig att de klarar av att
hantera den.

Det finns inga begränsningar för vad du kan använda visualisering till.
Det finns dock några grundläggande principer. De är:

1.  Släpp lite på tajta kläder, eller klä dig bekvämt. Lägg dig ned på
    en lugn plats och slut dina ögon mjukt.
2.  ”Skanna” din kropp: Rikta uppmärksamheten genom kroppsdel för
    kroppsdel och lägg märke till hur varje del känns. Gå från topp till
    tå eller tå till topp. Lägg märke till vilka muskler som är spända.
    Försök slappna av i de musklerna, så mycket det går.
3.  Börja med att skapa en mental bild som involverar alla dina sinnen:
    synen, hörseln, känseln samt lukt- och smaksinnet. Tänk dig till
    exempel att du är på en strand. Se färgerna i vattnet, himlen och
    sanden. Se människorna omkring dig, lägg märke till vad de har på
    sig och hur de ser ut. Lukta på havet och den rena, friska luften.
    Känn värmen av solen och den milda brisen mot din hud, känn sanden
    mellan tårna. Hör vågorna, ljudet av fåglarna och människorna runt
    omkring. Smaka på saltet i luften.
4.  Använd jag-budskap till dig själv för att rikta avslappningen.
    Använd presens och undvik negationer. Undvik till exempel att säga
    ”Jag är inte spänd”, vilket innehåller en negation (’inte’). Testa
    istället till exempel ”Jag slappnar av fullständigt”.
5.  Gör visualiseringsövningen tre gånger om dagen. Allra enklast är det
    att göra övningen på morgonen och på kvällen.

När du har övat på visualisering ett slag kommer du kunna använda
tekniken för att sänka spänningsnivån i de flesta situationer.
