---
lang: sv
title: Medveten närvaro för ökad toleransförmåga
---

Du har säkert hört människor prata om vikten av att kunna vara medvetet
närvarande i nuet. Medveten närvaro är inte riktigt detsamma som avslappning, även om många som tränar medveten närvaro också brukar rapportera att de blir mer avslappnade när de gör det.
Avslappning är dock inte alls målet med medveten närvaro -- man kan faktiskt vara helt medvetet närvarande även när man har en stark stressreaktion.
Att vara medvetet närvarande handlar om att ta in och uppleva det som
händer precis just nu, utan att värdera eller döma det. Det är en
färdighet som är mycket hjälpsam för att klara av att ”ta sin ångest i handen” och göra det som är viktigt i stunden. 

## Öka din förmåga att agera medvetet genom träning

Träning i medveten närvaro handlar om att ta in hela situationen,
inklusive alla de dömande tankar, känslor, kroppsförnimmelser och impulser som kommer och går (som upplevelserna alltid gör). Om du är extremt stressad inför en
presentation på jobbet, skulle medveten närvaro kunna handla om att
uppmärksamma att du är väldigt nervös och tänker dömande tankar som
”jag kommer aldrig klara det”. Och att sedan ändå fortsätta med det
som är viktigt, utan att trycka bort den negativa tanken
eller känslan. Det är lite som att säga ”Hej! Där är visst du igen!”
till den dömande tanken, utan att för den skull köpa det den dömande
tanken säger. Det är omöjligt att ta distans och perspektiv på tankarna och att samtidigt helt och hållet köpa sina tankar. Medveten närvaro gör på så sätt smärtsamma upplevelser mindre styrande.

Som med allt annat är det vettigt att börja träna på att praktisera medveten närvaro
långt innan du hamnar i en skarp situation. Det fungerar ungefär som när du tränar på gymmet. Själva hanteln är ett verktyg som hjälper dig att få starkare muskler. De flesta tränar inte muskelstyrka för att kunna bära omkring på hantlar, utanför att få ett bättre vardagsliv, om det så handlar om att vara nöjd med sin figur på stranden eller att klara av att bära hem matkassar från affären. Tänk på guidade övningar i medveten närvaro som hantlar eller andra redskap: De är i sig tämligen meningslösa, men hjälper dig att öva upp faktiskt mental styrka som du senare kan använda för att tänka och handla mer flexibelt i verkliga livet -- inklusive i skarpa situationer.

Här är en portabel övning (som du
kan såväl stående som gående) på Spotify från psykologen Fredrik
Livheim.

::: {.content-visible when-format="html"}
<iframe style="border-radius:12px" src="https://open.spotify.com/embed/episode/3dRaQwCRT2Nb2ASCa3L6pa?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
:::

Här är ytterligare några medveten närvaro-övningar som du kan prova, från Stressmottagningen. 

::: {.content-visible when-format="html"}
{{< video https://www.youtube.com/embed/y7PAGIOMX6I >}}
:::

::: {.content-visible when-format="html"}
{{< video https://www.youtube.com/embed/gGi03lwf_bw >}}
:::

::: {.content-visible when-format="html"}
{{< video https://www.youtube.com/embed/4kVAHhJted8 >}}
:::

## Planera för träning i progressiv avslappning

Mängdträning hjälper dig att automatisera nya färdigheter, så även med medveten närvaro. Ge dig de bästa möjliga oddsen för allt högre grad av medveten närvaro i vardagen genom att planera för din träning. Kom ihåg att det inte är övningen i sig som är viktig, utan den ökade mentala flexibilitet som du vinner av att öva regelbundet och över tid.

::: {.content-visible when-format="html"}
[Planera för framgång (PDF)](forms/100respekt-planera-traning.pdf)
:::

Har du använt arbetsbladet ovan och tänkt till om hur du kan hjälpa dig själv att
träna medveten närvaro? Om ja, så bra! Det kommer att hjälpa dig att gå
från ord till handling.