---
lang: sv
title: Sammanfattning
---

-   För att du ska kunna hävda dig själv behöver du bli medveten om när
    du blir fysiskt spänd och fysiskt uppjagad och lära dig att
    reglera kroppsreaktionerna, och/eller öka förmågan att tolerera dem. Hög fysisk spänning är en stor del av den upplevda stressnivån. I extremfall kan långvarig spänning
    leda till kronisk smärta och stressrelaterade sjukdomar.
-   Det finns flera sätt att sänka spänningsnivån, inklusive meditation,
    träning, tai chi, massage, visualisering, yoga, progressiv
    avslappning och långsam medveten andning.
-   För att minska stressnivån är det viktigt att vi övar på
    avslappningstekniker på daglig basis. Utforska och pröva dig fram
    bland de många olika teknikerna för att hitta en som passar just
    dig.
-   Du kan också hitta avslappningsövningar på strömmade video- och musiktjänster
    eller i appar till mobilen. Ett tips för att komma igång direkt:
    Spela in dig själv med mobilen när du läser [textmanuset till
    progressiv avslappning](5-3.qmd).
-   En annan färdighet är medveten närvaro. Medveten närvaro handlar om att så långt det bara är
möjligt ta in situationen här-och-nu, inklusive obehaget och de negativa tankarna. Träning i medveten närvaro är i första hand att öka förmågan att tolerera obehaget, genom att ta nya perspektiv på det. Det är omöjligt att samtidigt ta distans och perspektiv på tankarna och att ”köpa” sina tankar. Medveten närvaro gör på så sätt smärtsamma upplevelser mindre styrande.
-   Oavsett om du med avslappning ökar förmågan att reglera ned obehag eller om du med medveten närvaro ökar förmågan att tolerera det (eller båda sakerna samtidigt) kan du lättare ta sikte på det som är viktigt för dig i situationen. Du får då ökad förmåga att välja ditt handlande. Det underlättar för dig när du tränar på konstruktiv självhävdelse.

