---
lang: sv
title: "Övning: Planera inför de kommande två veckorna"
---

Under de två kommande veckorna kommer du att få fördjupa dig i ett eller
två av fyra områden som är viktiga för konstruktiv självhävdelse. Härnäst väljer du en eller
flera av de återstående avsnitten att göra övningarna i -- utifrån din egen nyfikenhet och vad du
helst önskar att träna på.

-   Du kan välja att titta närmare på varför det ibland är svårt att [säga
    ’nej’](6-0.qmd)\xpageref{sec-sayno}, och hur vi kan bli bättre på det. Det är viktigt för att
    minska stressen i livet.
-   Du kan också öva på hur du kan [hantera kritik](7-0.qmd)\xpageref{sec-critique} på ett
    konstruktivt sätt. Att kunna ta och ge kritik på ett konstruktivt
    sätt är bra för självkänslan.
-   Ett annat område du kan välja att jobba med är att [hantera besvikelser](8-0.qmd)\xpageref{sec-disappointments} på ett
    sätt som respekterar både dina egna och andras rättigheter.
-   Slutligen kan du öva på att [ta emot och ge komplimanger](9-0.qmd)\xpageref{sec-compliments} på ett självhävdande och konstruktivt sätt. Det är en viktig självhävdande och social färdighet.

Tänk tillbaka på dina SMARTa målsättningar och allt du har lärt dig
i avsnitten hittills. Lägg till alla de erfarenheter och
kloka slutsatser du har gjort i anslutning till de beteendeexperiment som du har utfört. Vad skulle vara ett lämpligt nytt område att
fortsätta din mängdträning i kontstruktiv självhävdelse inom?

Fortsätt använda dig av det här arbetsbladet, när du nu planerar dina kommande veckor. Du kan använda det här arbetsbladet så många gånger som du behöver.

::: {.content-visible when-format="html"}
[Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf){.bi-filetype-pdf}
:::
\xqrform{Mina mål: Självhävdelsebeteenden att öka (PDF)}{forms/100respekt-SMARTa-mal.pdf}

::: {.content-visible when-format="html"}
[Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-2-SMARTa-mal.pdf){.bi-filetype-pdf}
:::
\xqrform{Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)}{forms/100respekt-exempel-2-SMARTa-mal.pdf}

Och planera och utvärdera sedan dina beteendeexperiment med hjälp av det här arbetsbladet.

::: {.content-visible when-format="html"}
[Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf){.bi-filetype-pdf}
:::
\xqrform{Planera och genomför ett beteendeexperiment (PDF)}{forms/100respekt-beteendeexperiment.pdf}

::: {.content-visible when-format="html"}
[Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf){.bi-filetype-pdf}
:::
\xqrform{Exempel: Planera och genomför ett beteendeexperiment (PDF)}{forms/100respekt-exempel-beteendeexperiment.pdf}
