---
lang: sv
title: Att säga ’nej’ i underskott
---

Många personer har stora svårigheter att säga ’nej’ till andra. Även
personer som i andra situationer kan vara bra på att hävda sig själva
kan märka att de hamnar i situationer där de säger ’ja’ till saker som
de egentligen inte vill ställa upp på. Nu bör det sägas att det i vissa
situationer kan vara lämpligt att säga ’ja’, fast du helst inte vill
det. Om din chef till exempel ber dig om något väldigt viktigt som du är
anställd för att göra, är det nog inte det bästa tillfället att öva
självhävdelse i. Då kanske du riskerar att få sparken. Det vi menar här
är andra situationer där du märker att du säger ’ja’ mot din vilja. Ett
exempel kan vara att en god vän ber om hjälp med något som är väldigt
besvärligt för dig eller som du egentligen inte har tid för och du ändå
säger ’ja’. Eller att du säger ’ja’ till alla möjliga slags extra
arbeten och uppgifter till den grad att du blir överbelastad.

## Vanliga följder av att inte kunna säga ’nej’

Om du har för vana att säga ’ja’ när du egentligen vill säga ’nej’, kan
det leda till att du bygger upp ilska och förakt mot den person du sagt
’ja’ till -- även om den personen inte har gjort något fel. Det kan
också göra att du känner dig alltmer frustrerad och besviken på dig
själv. Om du tar på dig mer än du orkar med kan du bli överarbetad och
stressad. På lång sikt kan bristande självhävdelse av det här slaget
leda till sämre självkänsla, depression och ångest.

Det omvända kan också gälla: Kanske är du bara alltför bra på att säga
'NEJ!' -- men på ett sätt som är aggressivt och utan att du tar hänsyn
till den andra personens rättigheter. Det kan resultera i att den andra
personen blir arg eller sårad och kanske tar avstånd från dig.

Inget av alternativen ovan är exempel på konstruktiv självhävdelse.

## Hindrande förutsägelser, som gör det svårt att säga ’nej’

Vi har konstaterat att [vi människor föds med en självklar förmåga att hävda
oss själva](1-2.qmd). Alla som någon gång har umgåtts med en treåring vet att
treåringar inte har några som helst problem att säga ’nej’. Under vår
uppväxt lär vi oss dock nya sätt att svara på vår omgivning och våra
erfarenheter kanske inte längre säger att det är lämpligt att säga
’nej’. Det kan resultera i att vi skaffar oss olika slags övertygelser
om att det är dåligt för oss att göra det. Några av dessa hindrande
förutsägelser och övertygelser finns i listan nedan. Läs den och se om
några av dem stämmer för dig.

- Att hävda behov eller säga ’nej’ är oförskämt och aggressivt, det visar att jag är självisk och inte bryr mig om andra.
- Om jag hävdar behov eller säger ’nej’ kommer den andra personen att bli upprörd och känna sig avvisad.
- Om jag hävdar behov eller säger ’nej’ till någon kommer den personen inte längre att tycka om mig.
- Andras behov är viktigare än mina behov.
- Jag måste alltid försöka behaga och hjälpa andra.
- Att säga ’nej’ till småsaker är larvigt och småsint.

## Dina egna hindrande förutsägelser/antaganden

Tänk dig en situation där du kämpar med att säga nej. Vilka
förutsägelser gör du om vad som ska hända om du säger ’nej’? Vilka
förutsägelser gör du om din förmåga att klara av det som skulle hända om
du sa ’nej’? Skriv ned dem i arbetsbladet.

::: {.content-visible when-format="html"}
[Hindrande antaganden om att säga ’nej’ (PDF)](forms/hindrande-antaganden-saga-nej.pdf)
:::
