---
lang: sv
title: Effektiva sätt att säga 'nej'
---

Vi har nu gått genom något av det tänkande som kan hindra dig från att
säga 'nej'. Men även om du har koll på hur du tänker, kanske du inte vet
hur du ska handla. Det finns några grundläggande principer som du kan
tillämpa när du vill säga 'nej'.

## Olika sätt att säga 'nej'

Det finns flera sätt att säga 'nej' på. Vissa är mer lämpliga än andra i
specifika situationer. I boken *Free Yourself from Harmful Stress* av
Powell (1997) beskrivs sex olika sätt att säga 'nej' på. När du vill
säga 'nej' kan du välja bland följande:

1.  **Ett direkt 'nej'.** När någon ber dig att göra något som du inte
    vill, säg bara 'nej'. Målet är att säga nej, utan att be om ursäkt
    för det. Den andra personen äger problemet och du behöver inte låta
    honom eller henne föra över det på dig. Den här tekniken kan vara
    mycket kraftfull och effektiv med påstridiga säljare.
2.  **Ett inkännande 'nej'.** Den här tekniken innebär att du erkänner
    motpartens känslor och innehållet i hans eller hennes begäran, samt
    lägger till ditt självhävdande avslag på slutet. Ett exempel: "Jag
    vet att du vill prata med mig om hur vi ska lägga upp den årliga
    revisionen, men jag kan inte komma loss till lunchen idag." Ett
    annat exempel: "Jag vet att du ser fram emot att promenera i
    eftermiddag, men jag kan inte komma."
3.  **Ett förklarande 'nej'.** Med den här varianten ger du helt kort
    ditt genuina skäl till att du säger 'nej', till exempel "Jag kan
    inte äta lunch med dig idag eftersom jag måste bli klar med en
    rapport till imorgon."
4.  **Ett uppskjutande 'nej'.** Det här är faktiskt inte ett definitivt
    'nej'. Det är ett sätt att säga 'nej' till förfrågan just nu, men
    som håller öppet för att säga 'ja' i framtiden. Använd tekniken
    endast om du genuint vill möta begäran. Exempel: "Jag kan inte äta
    lunch med dig idag, men jag skulle kunna någon dag nästa vecka".
5.  **Ett undersökande 'nej'.** Precis som med den uppskjutande
    varianten är det är inte ett slutgiltigt 'nej'. Med det här sättet
    öppnar du begäran för att se om det finns något annat sätt att möta
    den, till exempel så här: "Är det någon annan dag som du skulle
    vilja luncha?"
6.  **Ett repig grammofonskiva-'nej'.** Det här sättet kan användas i
    många olika situationer. Du upprepar din enkla vägran, om och om
    igen. Du ger ingen förklaring. Du bara repeterar din vägran. Det är
    särskilt effektivt vid envetna frågor.

## Exempel på ett upprepat repig grammofonskiva-nej

Om du inte redan har spelat upp den här filmen, titta på den för att se
ett exempel på ett nej som upprepas flera gånger.

 
