# Sammanfattning och återkoppling på innehållet

-   Att säga 'nej' är svårt för många människor.
-   Som små barn har vi inga problem att säga 'nej', men när vi lär oss
    av omgivningen och våra erfarenheter kan vi utveckla svårigheter att
    göra det.
-   Att säga 'ja' när vi egentligen menar 'nej' är ett recept på stress,
    självförakt och ilska.
-   Om vi har svårt att säga 'nej' är det ofta för att vi har ett antal
    hindrande förutsägelser om vad som ska hända när vi gör det. Ett
    sätt att frigöra sig från dem är att upptäcka att de är mer eller
    mindre sannolika antaganden, snarare än fakta. Du kan
    använda beteendeexperiment för att utmana dina hindrande
    förutsägelser och få kontakt med alla fördelar som finns med att
    säga 'nej'.
-   Tre enkla råd för att göra det lättare att säga 'nej': håll ditt
    budskap kort, var tydlig och var ärlig.
-   Det finns många sätt att säga 'nej' på. De inkluderar ett direkt
    nej, ett undersökande nej, ett uppskjutande nej, ett förklarande nej
    och ett repig grammofonskiva-nej. 

## Vill du säga 'ja' eller 'nej' till inehållet i den här modulen?

##0b299e39357cde93c15d3e1ec537b8d4=
