---
title: Vad är kritik?
---

Vi har alla blivit kritiserade i livet. Att klara av att ta emot kritik
på ett konstruktivt och självhävdande sätt är en av de viktigaste saker
vi ställs inför på vår utvecklingsresa mot allt större grad av mognad.
Ordet 'kritik' kommer från ett gammalt grekiskt ord som beskriver en
person som sakligt ger ett omdöme, en analys, en värdering, en tolkning
eller en observation till någon annan. För att kunna acceptera kritik på
ett moget sätt behöver vi alltså kunna ta emot återkoppling på vårt
handlande från andra. Denna återkoppling kan komma i form av analyser,
observationer eller tolkningar.

## Olika slags kritik

Kritik kan antingen vara konstruktiv eller destruktiv. Konstruktiv
kritik är utformad för att ge genuin återkoppling på ett hjälpsamt och
icke-hotande sätt, för att personen som får kritiken ska kunna lära sig
något nytt och växa i något visst avseende. Återkopplingen är typiskt
valid, det vill säga att det är en sann kritik, exempelvis "Jag tyckte
mycket om hur du skrev rapporten; jag tror att den kan bli ännu bättre
om du ägnar tid åt att förbättra din stavning." Destruktiv kritik är
varken valid eller sann, eller så är den valid men ges på ett sätt som
är extremt ohjälpsamt. Den destruktiva kritiken ges ofta av någon som
inte har tänkt eller ordentligt, eller som vill skämma ut eller skada
mottagaren, exempelvis "Den här rapporten är gräslig, din stavning är
förskräcklig."
