# Varför reagerar vi som vi gör?

Hur vi tar emot kritik hänger till stor del samman med våra upplevelser
av att bli kritiserade som barn. Om vi inte har några tidigare
erfarenheter av att bli kritiserade kan vi bli helt förkrossade när vi
för första gången får kritik. Om vi som barn fick mycket konstruktivt
kritik klarar vi kanske av att ta emot kritik väl när vi växer upp. Om
vi fick hård och bestraffande kritik, kan vi däremot uppfatta all slags
kritik som sårande och avvisande.

Det senare händer ofta när kritiken handlade om oss som personer snarare
än om våra beteenden. Om du till exempel som barn gjorde ett misstag och
fick höra någon säga "du är dålig", säger kritiken underförstått att det
var du som person som var dålig. Sådan kritik är avvisande och kan få
dig att känna att förändring är utsiktslös. Om du däremot fick veta att
"det där var en dålig sak du gjorde", så är det lättare att skilja på
beteendet och personen. Det var beteendet som var dåligt, inte du som
person. Därmed står det också i din makt att förändra ditt handlande.

## Hur tar du kritik?

Hur tar du emot kritik från andra? Här är några vanliga sätt att svara
på kritik, som inte är exempel på självhävdelse:

-   Bli förvirrad
-   Bli defensiv
-   Larva sig
-   Ignorera kritiken utåt men bli sårad inombords
-   Internalisera ilska och koka inombords
-   Hämnas med ilska och skuldbeläggande
-   "Stänga ned"
-   Dra sig undan
-   Lämna situationen

## När blev du senaste kritiserad?

Tänk tillbaka på när du senast själv blev kritiserad. Skriv ned vad det
var för situation och hur du regarade.

##75b2f4118ea834f0f8ca89dd2fff947e=

## Passiv respons på kritik

Om vi oftast svarar med passivitet på kritik, får vi svårigheter att ta
emot den konstruktivt. Kanske går vi bara iväg och känner oss sårade och
förvirrade. Eller så tenderar vi att hålla med om vilken kritik som
helst, oavsett om den är valid eller inte. Och så klandrar vi oss själva
för det. Exempel: "Ja, du har rätt, jag är ... jag är värdelös, jag
måste lägga av." Då kan vi tolka kritik av vårt beteende som ett
avvisande av oss\
själva som personer. Den typen av respons kan i sin tur leda till
nedstämdhet, ångest och låg självkänsla. Det känns som att världen är en
plats fylld med kritik -- och vi håller med om den!

En alternativ respons när vi får kritik är att skratta och sedan öppet
kritisera oss själva ännu mer, med attityden "Om jag kritiserar mig
själv ännu hårdare och gör det på ett skämtsamt sätt kommer ingen veta
hur sårad jag egentligen är." På lång sikt har den här responsen samma
effekt som att öppet hålla med om all kritik som vi får.

## Aggressiv respons på kritik

Om vi brukar svara aggressivt betyder det att vi tolkar kritik som en
attack på våra personer. När vi uppfattar att vi blir attackerade blir
vi defensiva och går kanske också själva till attack. Till exempel: "Hur
vågar du?! Jag är inte sen. Det är du som alltid är sen." Den här typen
av respons kan ofta leda till konflikt och aggression, vilket i sin tur
kan leda till nedstämdhet och låg självkänsla.

## Konstruktiv självhävdelse vid kritik

Att hävda sig själv vid kritik handlar om att identifiera och se
skillnad på konstruktiv och destruktiv kritik, och att handla därefter.
När vi hävdar oss själva konstruktivt förstår vi att kritiken inte
nödvändigtvis handlar om oss själva som personer. Vi blir inte
defensiva, arga, sårade eller klandrar oss själva. Vi springer inte
därifrån. Vi behåller lugnet och tar emot kritiken utan negativa
känslouttryck. I nästa avsnitt finns sätt att tänka som gör det enklare
att svara på kritik med konstruktiv självhävdelse.
