---
lang: sv
title: Tänkandet påverkar hur du agerar
---

## Hindrande förutsägelser

Som med andra icke självhävdande beteenden finns det ofta hindrande
förutsägelser om andras avsikter eller din förmåga att klara av kritik.
Här är några exempel på negativa förutsägelser eller regler som kan
styra handlandet:

-   ”Om jag blir kritiserad betyder det att jag är dum.”
-   ”Eftersom de kritiserade mig, tycker de inte om mig längre.”
-   ”De har rätt, jag gjorde fel, jag kan inte gör något rätt. Jag är
    misslyckad.”
-   ”Jag kan inte kritisera dem för då kommer de inte att tycka om mig.”
-   ”Hur vågar de säga att jag har gjort fel? De har ingen rätt att göra
    det.”
-   ”De är hur som helst idioter. Jag tänker inte lyssna på dem.”
-   ”Om jag kritiserar mig själv ännu hårdare och skojar om det kommer
    ingen att få veta hur sårad jag är.”

### Dina egna negativa förutsägelser

Kan du identifiera ytterligare hindrande förutsägelser, utifrån egna
faktiska tidigare erfarenheter, som gör det svårt för dig att möta
kritik med konstruktiv självhävdelse? Skriv upp dem.

::: {.content-visible when-format="html"}
[Hindrande antaganden om att ta/ge kritik (PDF)](forms/100respekt-hindrande-antaganden-hantera-kritik.pdf)
:::

## Hjälpande förutsägelser

Här är några hjälpsamma och självhävdande förutsägelser, som du kan
använda för att balansera negativa, hindrande förutsägelser som du kan
ha.

-   ”Om det är något fel på det jag gjort betyder det inte något om mig
    som person. Jag behöver skilja mellan mitt handlande och mig själv
    som person.”
-   ”Vad kan jag lära mig av kritiken? Det mesta av kritiken innehåller
    sannolikt ett korn av sanning. Kritik kan te sig negativt. Men varje
    gång jag får kritik har jag möjlighet att lära mig av den. Jag kan
    vill alltid fråga mig själv vad jag kan lära mig av kritiken.”
-   ”Jag har rätt att berätta att jag känner mig sårad, irriterad eller
    upprörd, av andras beteende.”
-   ”Att ge direkt återkoppling och kritik kan vara kärleksfullt och
    omtänksamt.”

### Dina egna hjälpande förutsägelser

Kan du komma på några andra konstruktivt självhävdande förutsägelser om
vad kritik innebär och/eller om din förmåga att klara av att få kritik?
Om du skrev upp några egna hindrande förutsägelser ovan, testa att
formulera egna balanserande förutsägelser till dem.

::: {.content-visible when-format="html"}
[Hjälpande antaganden om att hantera kritik (PDF)](forms/100respekt-hjalpande-antaganden-hantera-kritik.pdf)
:::

### Fortsätt arbeta med beteendeexperiment

Fortsätt att genomföra [beteendeexperiment](3-4.qmd) för att i praktiken hitta
egna bra anledningar att ge eller ta kritik. Kanske märker du att du har svårt
att tro på att dina nya beteenden kommer att fungera över tid. Det är helt
normalt. Du har förmodligen tänkt dina gamla tankar och utfört dina
säkerhetsbeteenden väldigt länge, så att de numera kommer helt automatiskt för
dig. Det kommer ta lite tid innan det nya handlandet blir lika automatiserat och
självklart som det gamla har varit. Fortsätt öva så kommer de att automatiseras.

::: {.content-visible when-format="html"}
[Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf)
:::
