---
lang: sv
title: Ta emot konstruktiv kritik
---

Vi behöver alla klara av att ta emot konstruktiv kritik. Du kan reagera
på flera olika sätt, beroende på hur kritiken framförs.

## 1. Acceptera kritiken

Om kritiken är valid, ta emot den utan att uttrycka skuld eller negativa
känslor. Acceptera att du inte är perfekt och att det enda sättet du kan
lära dig något är att testa, ibland göra misstag, se vad som behöver
ändras och testa igen. Tacka personen för återkopplingen, om det är
lämpligt. Se kritiken som en gåva.

## 2. Använd omvänd konstruktiv självhävdelse

Den här tekniken handlar inte bara om att acceptera kritiken, utan också
öppet hålla med om den. Den används när någon framför berättigad kritik
till dig. Den här färdigheten handlar om att lugnt hålla med om kritiken
av dina negativa egenskaper, utan att be om ursäkt eller för den skull
känna dig förkrossad.

Exempel:

**Kritik** -- Ditt skrivbord är väldigt stökigt. Du är desorganiserad.\
**Svar** -- Ja, det är sant. Jag är inte så ordentlig.

Nyckeln till omvänd konstruktiv självhävdelse är självförtroende och
övertygelsen att du har förmågan att ändra dig själv om du önskar göra
det. Genom att hålla med om och acceptera kritiken, om den är befogad,
så behöver du inte känna dig helt förstörd. Den här typen av svar kan
också användas för att desarmera spända situationer. Om någon kritiserar
dig aggressivt kan det bero på att hen förväntar sig att du ska svara
aggressivt. Spänningen släpper när du håller med personen.

Ett annat sätt att använda omvänd självhävdelse på ett konstruktivt sätt
är att ta ägarskap över ett misstag innan någon annan hinner påpeka det.
Om du till exempel kommer för sent kan du säga "Hej, jag är sen."

## 3. Använd omvänt, konstruktivt undersökande

Omvänt undersökande innebär att du på ett konstruktivt sätt ber om
fördjupad och mer specifik kritik. Om du blir osäker på om kritiken som
framförs är berättigad eller konstruktiv, kan du be om mer detaljer.

Exempel:

**Kritik** -- Det kommer inte bli så lätt för dig, eller hur, eftersom
du är blyg?\
**Svar**  -- På vilka sätt tycker du att jag är blyg?

Om kritiken är konstruktiv, kan informationen som kommer när du frågar
om mer detaljer användas på ett konstruktivt sätt. Då förbättras också
kommunikationen mellan dig och samtalspartnen. Om kritiken däremot är
manipulerande eller avsedd att såra visar du med dina frågor att den
inte är konstruktiv.
