---
lang: sv
title: Ta emot destruktiv kritik
---

Tyvärr kommer vi alla att stöta på destruktiv kritik någon gång under
våra liv. Destruktiv kritik är svårare att hantera än konstruktiv
kritik. Om vi övar på teknikerna nedan, kan vi bli skickligare på att
hantera dessa svåra situationer. Som med alla andra färdigheter i livet
krävs det övning och tar en hel del tid innan du känner dig säker på
dem. Lägg märke till att vissa av de här färdigheterna är samma
färdigheter som används för att hantera konstruktiv kritik.

## 1. Inte hålla med

Den första tekniken handlar helt enkelt om att inte samtycka till
kritiken. Det är viktigt att du behåller lugnet och tänker på dina
icke-verbala beteenden, inklusive röstläget. Det är lätt att glida över
i aggressivitet eller passivitet när du inte håller med om något. Se
personen i ögonen och svara med lugn röst.

Exempel:

**Kritik** -- Du är alltid sen.\
**Svar**  -- Nej, jag är inte alltid sen. Det händer ibland att jag är
sen, men jag är verkligen inte alltid sen.

## 2. Använda omvänt, konstruktivt undersökande

Som vi nämnde ovan kan det hända att du inte kan avgöra om kritiken som
framförs av någon annan är konstruktiv eller destruktiv. Vi behöver
förstå vad personen menar. Om kritiken är destruktiv kan vi antingen
inte hålla med om den, som i exemplet ovanför, eller använda en av de
avväpnande teknikerna nedan.

## 3. Använda avväpnande (eller uppluckrande) tekniker

De här teknikerna handlar om att på ett eller annat sätt göra kritiken
"luddig i kanterna", eller att "luckra upp den". Syftet med dem är att
desarmera en potentiellt aggressiv eller svår situation. Använd de här
teknikerna när kritiken varken är välgrundad eller konstruktiv. När vi
får destruktiv kritik är den vanligaste reaktionen för de flesta att
antingen svara med samma mynt, det vill säga att bli aggressiva och slå
tillbaka, eller att bli passiva och krypa ihop. Inget av dessa
alternativ är särskilt bra.

Tricket med de här teknikerna är att hitta ett sätt att hålla med om en
liten del av vad motparten säger. Genom att hålla lugnet och att inte gå
med på att bli provocerad eller upprörd, kan du använda teknikerna för
att dränera kritiken på dess destruktiva kraft.

Det finns tre olika slags avväpnande tekniker:

### (a) Delvis hålla med

Den här tekniken går ut på att du hittar en del av kritiken som är
befogad, och håller med om endast den delen.

Exempel 1:

**Kritik** -- Det går inte att lita på dig. Du glömmer hämta barnen, du
betalar aldrig hyran så nu riskerar vi att bli utan tak över huvudet och
du finns aldrig där för mig när jag behöver dig.\
**Svar**  -- Du har helt rätt i att jag glömde hämta barnen från
simträningen förra veckan.

Exempel 2:

**Kritik** -- Du jobbar inte, du gör precis ingenting.\
**Svar**  -- Ja, det är sant, jag har inget jobb.

### (b) Hålla med, men inte om sannolikheten

Med den här tekniken kan du hålla med om att ett utfall är möjligt, även
om du själv tror att sannolikheten för det utfallet är en på miljonen.

Exempel:

**Kritik** -- Om du inte använder tandtråd kommer du att tappa
tändernaoch det kommer du ångra resten av livet!\
**Svar**  -- Du har rätt, jag kan få tandlossning.

### (c) Hålla med i princip

Med den här tekniken håller du med om den andra personens logik, utan
att hålla med om innehållet i det han eller hon säger.

Exempel:

**Kritik** -- Det är fel verktyg för det du håller på med. Ett stämjärn
kan slinta och förstöra trästycket. Du borde använda ett håljärn
istället.\
**Svar**  -- Du har rätt, om stämjärnet slinter kommer det verkligen
förstöra träämnet.

## Extra tips när vi blir kritiserade

### 1. Svara på innehållet (orden) i kritiken, inte tonen

Det är viktigt att dela upp det som kritiken handlar om från sättet den
framförs på. När människor kritiserar andra uppfattas de ofta som
konfronterande eller till och med aggressiva. Det kan betyda att vi
avfärdar det de säger, trots att innehållet i kritiken faktiskt kan vara
användbart. Det krävs träning för att lyckas skilja på innehållet i
kritiken från stilen på kritiken. Även om personer pratar på ett argt
sätt, bör vi försöka att koppla loss oss från känsloläget i kritiken och
förhålla oss till de användbara förslag som finns därunder.

### 2. Svara inte direkt

Det kan vara bäst att vänta lite med att svara på kritik. Om vi svarar
direkt kan vi lätt göra det med arga känslor eller sårad stolthet,
vilket lätt kan få konsekvenser som vi sedan ångrar. Om vi skjuter in
lite tålamod ger det oss möjlighet att reflektera över kritiken i lugn
och ro, innan vi svarar.

### 3. När du känner dig kritiserad -- gör så här

1.  Stanna upp. Reagera inte förrän du är säker på vad som pågår.
2.  Fråga dig: har du verkligen blivit kritiserad? Eller försöker du
    "tankeläsa" den andra personen?
3.  Fråga personen. Om du är osäker, fråga! Till exempel: "Vad menade du
    med det där?"
4.  När du har rett ut om det verkligen handlar om kritik, utvärdera om
    den är befogad och valid, eller inte. Svara sedan med hjälp av någon
    av teknikerna i den här modulen.
