---
title: Ge konstruktiv kritik
---

Så här långt komna har vi pratat om färdigheter för att ta emot och
hantera kritik. Det finns också färdigheter att träna på för att ge
kritik. Dessa färdigheter handlar om att lägga fram kritiken på ett sätt
som gör det möjligt för personen som får kritiken att ta emot det du
vill säga. Du har all rätt att begära en ändring i någons beteende om
beteendet sårar, upprör eller irriterar dig på något sätt. Kom ihåg att
det inte är säkert att personen kommer att ändra sättet han eller hon
beter sig på även om du ber om det. Men genom att uttrycka dina behov
slipper du bygga upp harm och förbittring som skulle kunna ge ännu större
problem i relationen till den andra personen.

Att ge befogad kritik har ett värde i sig, oavsett om den efterlevs
eller inte. Rak och ärlig återkoppling kan vara uttryck för både omtanke
och hjälpsamhet. Det spelar ingen roll om kritiken är negativ eller
positiv -- när du uttrycker den visar du den andra personen att du
värderar honom eller henne, liksom relationen er emellan.

Försök att följa riktlinjerna nedan när du ger konstruktiv kritik.

1.  **Välj tid och plats noga.** Om du ger konstruktiv kritik om något
    som har orsakat en stark känslomässig reaktion, vänta tills du har
    lämnat den jobbiga situationen och hunnit lugna ned dig. Sedan kan
    du framföra din kritik. Vänta inte tills du hamnar i samma situation
    igen innan du konfronterar beteendet.
2.  **Beskriv beteendet du kritiserar, istället för att sätta
    "etiketter" på personen.** Säg till exempel hellre "Du fick med ett
    fel i rapporten" än "Är du dum i huvudet?"
3.  **Beskriv dina känslor med jag-budskap, utan att klandra den andra
    personen.** Säg till exempel "Jag blir arg när ..." snarare än "Du
    gör mig arg."
4.  **Be om en konkret förändring.** Säg till exempel hellre "Den höga
    musiken stör mig verkligen, vill du vara så vänlig att sänka
    ljudvolymen efter 20:00?" istället för "Jag står inte ut med din
    höga musik".
5.  **Ange konsekvenserna,** både de positiva konsekvenserna om personen
    efterföljer din begäran, och de negativa konsekvenserna om personen
    inte ändrar sitt beteende.
6.  **Ge realistiska förslag på förändring** och realistiska
    konsekvenser om personen inte följer din begäran. Uttala inte tomma
    hot. Säg till exempel inte "Jag slår ihjäl dig om du inte sänker
    volymen."
7.  **Fråga personen vad han eller hon tänker/känner** om det du nyss
    har sagt. Att hävda sig själv handlar om att ge förutsättningar för
    jämställd kommunikation. Var försiktig med att det här inte urartar
    till ett utbyte av kritik.
8.  **Försök avsluta i en positiv riktning.** Om det är lämpligt, lägg
    till en positiv beskrivning om dina känslor gentemot den andra
    personen.
