---
lang: sv
title: Hur hanterar du besvikelser?
---

Att behöva hantera besvikelser är en del av att vara människa. Ibland
blir saker och ting inte som man hade tänkt sig: förluster och
misslyckanden går helt enkelt inte att undvika. I det här avsnittet tittar
vi närmare på olika vanliga responser på besvikelser. Att handla
konstruktivt handlar inte om att inte tillåta sig att känna sig besviken
-- tvärtom! Att vara konstruktiv inför förluster och misslyckanden
handlar om att med självmedkänsla ge plats för obehaget och
ångesten samtidigt som du medvetet handlar på ett sätt som för dig
närmare det du värdesätter. Kommer du ihåg den [aktiva
cirkeln](3-2.qmd)?

Här är några vanliga sätt som människor kan hantera besvikelser på:

-   Dra sig undan och älta
-   Bli arg på saken eller personen som orsakat besvikelsen. Det kan
    inkludera att bli arg på sig själv.
-   Bli nedstämd
-   Vilja utkräva hämnd
-   Bli uppgiven
-   Kritisera sig själv

## Vad gjorde du senast du blev besviken?

Fundera en liten stund på när du senast blev besviken. Försök att komma
ihåg hur du reagerade -- med passivitet, konstruktiv självhävdelse eller
med aggressiv självhävdelse? Skriv ned det du kommer ihåg i arbetsbladet för dina SMARTa mål. Du kan under den här veckan välja att planera ett beteendeexperiment för en liknande situation i framtiden, som du därefter kan utvärdera nyfiket.

::: {.content-visible when-format="html"}
[Mina mål: självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf)

[Exempel 2: Mina mål: självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-2-SMARTa-mal.pdf)
:::

## Passiva svar på besvikelser

Om du reagerar på en besvikelse med passivitet är det troligt att du
också ger upp dina försök att gå i den önskade riktningen i livet. Då är
risken också stor att du blir överdrivet självkritisk för att du inte
kunde nå dit du ville. Det kan också hända att du tycker synd om dig
själv och drar dig undan för att älta. Om det är andra personer som har
gjort dig besviken, kanske du ger upp om dem också. Alla dessa
reaktioner kan försämra självkänslan och leda till nedstämdhet.

## Aggressiva svar på besvikelser

Om du svarar med aggressivitet på en besvikelse känner du dig sannolikt
arg på personen eller situationen som orsakade den. Risken ökar då att
du blir bitter på personen eller situationen. Kanske märker du också att
du blir hämndlysten.

## Konstruktiv självhävdelse vid besvikelser

Om du svarar med konstruktiv självhävdelse på en besvikelse, är det
mycket möjligt att du fortsätter att känna dig besviken över att saker
inte har gått din väg. Det är normalt! Det som är skillnaden mot de
andra svarsstilarna är att du varken klandrar dig själv eller någon
annan för hur saker har utvecklat sig. Det innebär också att du inte
fastnar i ett negativt känsloläge. Du tar ansvar för din del i
besvikelsen och tänker igenom vad du kan göra för att komma vidare från
det nuvarande läget. Det kan innebära att du måste ändra på något i
livet -- att det kan finnas något som du kan lära dig av din besvikelse.
Eller så finns det ingenting alls som du kan förändra. Oavsett så
handlar konstruktiv självhävdelse om att acceptera hur det har gått.
