---
lang: sv
title: Dina förutsägelser i situationen påverkar hur du agerar
---

Precis som med andra beteenden som vi har tittat på finns det både
hindrande och konstruktiva sätt att förhålla sig i situationer där du
blir besviken. Dessa förutsägelser är resultatet av både tidiga
smärtsamma upplevelser och de automatiska responser av undvikande som du
har byggt upp som en följd av dessa tidiga upplevelser. Utmaningen för
dig nu är att testa vilket utfallet blir om du frigör dig från dina
vanemässiga undvikanderesponser. När du ”tar ångesten i handen” lite
varsamt och utvärderar vad utfallet blir om du hävdar dig själv
konstruktivt när du blir besviken, kan du mycket väl upptäcka att dina
tidigare förutsägelser inte är hjälpsamma för dig. 

## Hindrande förutsägelser i situationen

Hur du hanterar en besvikelse hör samman med vilka förutsägelser du gör
i situationen om vad effekterna blir av ditt handlande. Här är några
exempel på hindrande förutsägelser, som kan göra det svårt för dig att
hävda dig själv konstruktivt när du blir besviken.

-    ”De borde veta att jag inte gillar när de gör så där.”
-    ”Världen är hemsk, jag står inte ut med det här.”
-    ”Den personen är ond.”
-    ”Jag vägrar acceptera att den personen gör på det sättet.”
-    ”Jag tolererar inte det här, det är oacceptabelt.”

## Egna exempel på hindrande förutsägelser

Kan du hitta några andra tankar som hindrar dig från att svara på
besvikelser med att hävda dig själv konstruktivt?

[Hindrande antaganden om att hantera besvikelser (PDF)](forms/100respekt-hindrande-antaganden-hantera-besvikelser.pdf)

## Konstruktiva förutsägelser

Här är några exempel på hjälpsamma förutsägelser i situationer där du
blir besviken, som du kan läsa, utvärdera och testa. Kanske kan de göra
det lättare för dig att hävda dig själv konstruktivt när du blir
besviken? Kom ihåg att det bästa sättet att komma i kontakt med sådant
som du värdesätter är att göra beteendeexperiment. Utifrån de slutsatser
du drar av dina beteendeexperiment kan du utveckla nya, hjälpsamma
förutsägelser om vad det innebär för dig att reagera konstruktivt när du
blir besviken.

-   ”Det är inte roligt att bli orättvist behandlad, men det är inte
    heller fruktansvärt eller katastrofalt.”
-   ”Jag kan stå ut med att vara sårad och frustrerad. Jag kan göra
    något för att påverka situationen.”
-   ”Jag accepterar hur den andra personen är. Han eller hon har kanske
    avvisat en del av mina beteenden men inte hela mig som person.”
-   ”Det är bäst att jag öppet uttrycker mina känslor; konsekvenserna av
    det behöver inte bli så hemska som jag tror.”

## Dina egna hjälpsamma förutsägelser

Försök hitta egna tankar om värdet av att hävda dig själv konstruktivt,
även när du blir besviken. Om du hittade egna hindrande tankar ovan,
försök att också hitta egna balanserande tankar till dem.

[Hjälpande antaganden om att hantera besvikelser (PDF)](forms/100respekt-hjalpande-antaganden-hantera-besvikelser.pdf)

## Fortsätt arbeta med beteendeexperiment

Fortsätt att genomföra [beteendeexperiment](3-4.qmd) för att i praktiken hitta egna bra anledningar hävda dig själv
konstruktivt när du har blivit besviken. Kanske märker du att du har
svårt att tro på att dina nya beteenden kommer att fungera över tid. Det
är helt normalt. Du har förmodligen tänkt dina gamla tankar och utfört
dina säkerhetsbeteenden väldigt länge, så att de numera kommer helt
automatiskt för dig. Det kommer ta lite tid innan det nya handlandet
blir lika automatiserat och självklart som det gamla har varit. Fortsätt
öva så kommer de att automatiseras.
