# Mängdträna på att hantera besvikelse

Kommer du ihåg det vi skrev om *multiple exemplar training* i **[modul
2](https://www.iterapi.se/sites/respekt/program/2-skillnader-mellan-olika-kommunikationsstilar/72-lite-om-inl-rning-obehag-och-motivation)** --
att nya färdigheter är resultatet av mängder av upprepade
övningstillfällen? Med träning i din egen vardag kan du som vi såg i
**[modul
3](https://www.iterapi.se/sites/respekt/program/3-utmana-negativa-f-ruts-gelser-med-beteendeexperiment/15-argument-f-r-att-byta-undvikande-mot-aktivt-deltagande)** allt
mer automatiserat ersätta ovanan att undvika ångest i svåra situationer
med den goda vanan att hävda dig själv konstruktivt. Du gör det genom
att ta fasta på det viktiga som ångesten skvallrar om och sedan aktivt
göra det du värdesätter.

## Träna på att bli din egen terapeut!

De kommande två veckorna i det här träningsprogrammet är vikta åt
mängdträning i det eller de områden som du vill träna konstruktiv
självhävdelse inom. Gör ett eller två beteendeexperiment i den här
modulen, och gärna något eller några i ytterligare någon av de andra
modulerna. I den sista veckan (veckan innan påsk som slutar 5 april)
kommer du att få hjälp att \"knyta ihop säcken\" genom att inventera
dina styrkor, utarbeta en handlingsplan vid bakslag och planera för
vidmakthållande av de färdigheter du har vunnit under programmet.

## Det kan vara svårt att PLANERA besvikelser

Det är inte lätt att planera att bli besviken. Men om du tränar på att
**[ge och ta emot
komplimanger](https://www.iterapi.se/sites/respekt/program/9-ge-och-ta-emot-komplimanger-konstruktivt)**,
**[ge och ta
kritik](https://www.iterapi.se/sites/respekt/program/7-hantera-kritik-konstruktivt)**
eller **[säga nej och att sätta
gränser](https://www.iterapi.se/sites/respekt/program/6-s-ga-nej-konstruktivt)**
kommer du att märka att det inte alltid går som du vill och hoppas. Ett
smart sätt att dra nytta av sådana potentiella bakslag är att då passa
på att träna på att hantera besvikelser på ett konstruktivt sätt. Då
maximerar du din inlärning, hur det än går!

## Mängdträna med omväxlande svårighetsgrad

När du övar på dessa tekniker: Planera, genomför och dokumentera dem som
beteendexeperiment. Utgå från din första SMARTa målsättning eller välj
en ny situation som du vill träna i. Genomför ditt beteendeexperiment på
precis samma sätt som det du har genomfört tidigare i det här
träningsprogrammet, men se om du kan lägga till någon av teknikerna från
den här modulen. Det kommer att kännas ovant och konstlat till en
början, men genom att pröva teknikerna och sedan utvärdera utfallen kan
du hitta de sätt som ger dig framkomlighet för dig.

Du kan använda formuläret nedan hur många gånger du vill: När du har
fyllt i det en första gång kommer det automatiskt visas en länk ovanför
det som du kan använda för att skapa en ytterligare version av
formuläret.

Sikta på att utföra åtminstone 2 olika beteendeexperiment den här
veckan. Ju fler tillfällen du tränar, desto bättre! Om du tidigare har
genomfört ett svårt beteendeexperiment, gör då gärna ett litet lättare
härnäst. Du förtjänar att också få bokföra lite enklare vunna
framgångar.

##50f348a03aa09cf8bb5e9ba6a6c6ce69=
