---
title: Komplimanger bygger relationer och självkänsla
---

Att ge och ta komplimanger är en annan färdighet som har med
självhävdelse att göra, eftersom det är en viktig del av vardagliga
konversationer, byggande av relationer och utvecklande av självkänsla.
Precis som med alla andra färdigheter som vi har fördjupat oss i, så
hindrar vårt sätt att tänka ofta vår förmåga att ta emot och ge
komplimanger. Det kan också vara så att vi saknar färdigheter som behövs
för att i nästa steg kunna utveckla färdigheten att ta emot och ge
komplimanger. Den här modulen hjälper dig att identifiera dina hindrande
tänkande (antaganden och förutsägelser som du gör), och visar också
stegvis hur du kan göra för att förbättra sättet som du förhåller dig
till komplimanger på.

## Ta emot komplimanger

Många tycker att det är extremt svårt att ta emot komplimanger. Det är
förståeligt att det ibland känns obekvämt att få beröm, men det är en
viktig social färdighet för självhävdelse att konstruktivt kunna ta emot
andra människors positiva kommentarer om vårt utseende, vårt arbete
eller andra aspekter av oss själva.
