---
lang: sv
title: Hur hanterar du komplimanger?
---

Sättet man kan ta emot komplimanger på som inte är uttryck för
självhävdelse är många. De inkluderar:

-   Ignorera komplimangen och byta samtalsämne
-   Säga emot en del av eller hela komplimangen, exempelvis ”Faktiskt
    tycker jag inte om färgen på tröjan alls.”
-   Avfärda eller låta komplimangen rinna av sig, till exempel ”Åh, det
    här gamla loppisfyndet, det är inget särskilt.”
-   Vara sarkastisk. Till exempel: ”Javisst, den är ju helt fantastisk,
    eller hur?”
-   Le eller skratta nervöst
-   Börja tala självkritiskt

## Hur tog du senast emot en komplimang?

När fick du senast ta emot en komplimang? Fundera en stund på det och se
om du kan komma ihåg hur du reagerade. Beskriv situationen och hur du
reagerade. Var din reaktion passiv, självhävdande eller aggressiv? Skriv ned det du kommer ihåg i arbetsbladet för dina SMARTa mål. Du kan senare välja att planera ett beteendeexperiment för en liknande situation i framtiden, som du därefter kan utvärdera nyfiket.

::: {.content-visible when-format="html"}
[Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-SMARTa-mal.pdf)
:::
\xqrform{Mina mål: Självhävdelsebeteenden att öka (PDF)}{forms/100respekt-SMARTa-mal.pdf}

::: {.content-visible when-format="html"}
[Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)](forms/100respekt-exempel-2-SMARTa-mal.pdf)
:::
\xqrform{Exempel 2: Mina mål: Självhävdelsebeteenden att öka (PDF)}{forms/100respekt-exempel-2-SMARTa-mal.pdf}

## Passiva svar på komplimanger

Om du svarar passivt på komplimanger är det sannolikt att du antingen
ignorerar komplimangen helt, avleder uppmärksamheten från den eller
minimerar berömmet. Möjligen gör du detta för att du känner dig nervös
eller obekväm och inte vet vad du ska göra. Det kan resultera i att den
andra personen också känner sig obekväm. Kanske går du då från
situationen med en känsla av förlägenhet. Då kan självkänslan ta en
smäll.

## Aggressiva svar på komplimanger

Om du blir irriterad, arg eller defensiv, eller säger emot eller svarar
sarkastiskt på berömmet -- då är ditt svar aggressivt. Det kan få den
andra personen att känna sig obekväm, precis som vid passiva svar.

## Självhävdande svar på komplimanger

Om ditt svar bygger på att du hävdar dig själv, och låter dig ta plats i
situationen, så tar du emot komplimangen på ett positivt sätt, både för
dig själv och avsändaren. Den andra personen känner sig bekväm och
interaktionen leder till att ni båda mår bättre. Du mår bättre eftersom
du accepterade komplimangen. Den andra personen mår bättre eftersom han
eller hon fick ge dig den.

Att välja att ta emot komplimanger kräver en hel del arbete. Till att
börja med måste du aktivt bortse från den självkritik som med all
sannolikhet dyker upp. Den kommer automatiskt, som ett resultat av lång
tids träning på att formulera självkritik. Därefter behöver du träna på
att agera som om du trodde på komplimangen, även om det till en början
känns krystat. När du till slut har lärt dig att omfamna positiv
återkoppling och ta emot komplimanger på ett vänligt sätt öppnar det
dörren för ännu fler varma tankar och positiva interaktioner. Så
småningom kan du faktiskt börja tro på komplimangerna!