---
lang: sv
title: Dina förutsägelser påverkar hur du agerar
---

Våra förutsägelser i olika situationer kan göra att vi undviker att
hävda oss själva även i situationer när vi får komplimanger. Vi kan
pröva dessa förutsägelser i beteendeexperiment, vilket både sätter oss i
kontakt med sådant som är viktigt och gör det möjligt för oss att
formulera mer hjälpsamma förutsägelser om vad det innebär att ta emot en
komplimang.

## Negativa förutsägelser om komplimanger

Samma sak gäller för situationer där vi får komplimanger, som för många
andra situationer som du får jobba med i det här materialet. Här är några av
de hindrande förutsägelser som vi kan ha i situationer där vi får beröm
eller uppskattning:

-   ”De menar det inte egentligen. De försöker bara vara trevliga.”
-   ”De är inställsamma.”
-   ”De är ute efter något.”
-   ”Om jag tar emot komplimangen betyder det att jag är högfärdig.”
-   ”Om jag tar emot komplimangen tror de att jag är fåfäng.”
-   ”Det är alldeles för pinsamt för att jag ska kunna säga något
    tillbaka.”

### Dina egna negativa förutsägelser om att ta emot komplimanger

Kan du identifiera några andra hindrande förutsägelser som du har, som
gör det svårt för dig att hävda dig själv och ta plats när du tar emot
komplimanger? Skriv upp dem här:

::: {.content-visible when-format="html"}
[Hindrande antaganden om att ta/ge komplimanger (PDF)](forms/100respekt-hindrande-antaganden-hantera-komplimanger.pdf)
:::

## Exempel på hjälpsamma förutsägelser

Här är några hjälpande förutsägelser som du kanske samtidigt har, som du
kan använda för att balansera dina hindrande förutsägelser. Med
beteendeexperiment kan du pröva dina negativa förutsägelser i
situationer som tidigare har varit svåra för dig, och på så sätt göra
allt fler hjälpsamma och realistiska förutsägelser som ger dig möjlighet
att hävda dig själv.

-   ”Komplimangen kan vara äkta.”
-   ”Även om de bara försöker vara vänliga så är det en positiv sak och
    jag vill svara på ett lämpligt sätt.”
-   ”Om jag inte tar emot komplimangen kommer jag att få den andra
    personen att känna sig obekväm.”
-   ”Om jag tar emot komplimangen kan jag få den andra personen att
    också må bättre.”
-   ”Även om jag tar emot en komplimang på ett vänligt sätt behöver jag
    inte hålla med om den helt och hållet.”
-   ”Om jag börjar att tro på en del komplimanger kommer jag inte känna
    mig lika dålig längre.”
-   ”Att jag tar emot en komplimang betyder inte att jag är uppblåst
    eller tror att jag är bättre än andra. Om så vore fallet skulle jag
    ju redan ge mig själv massor av komplimanger!”
-   ”Människor ger komplimanger av massor av olika skäl. Det är inte
    lönt att slösa tid på att undra varför någon gjorde det mot mig. Jag
    vill uppskatta det faktum att någon tog sig tid att säga något
    snällt till mig!”
-   ”Jag har lika mycket rätt till komplimanger som någon annan.”

### Egna exempel på hjälpande förutsägelser

Kan du hitta några fler förutsägelser utifrån egna erfarenheter, som kan
hjälpa dig att hävda dig själv i tuffa situationer? Använd dem (eller
några av ovanstående, som du tror på) för att balansera de negativa,
hindrande förutsägelserna du skrev ned här ovan.

::: {.content-visible when-format="html"}
[Hjälpande antaganden om att ta/ge komplimanger (PDF)](forms/100respekt-hjalpande-antaganden-hantera-komplimanger.pdf)
:::

### Fortsätt arbeta med beteendeexperiment

Fortsätt att genomföra [beteendeexperiment](3-4.qmd) för att i praktiken hitta egna bra anledningar hävda dig själv
konstruktivt när ger och tar emot komplimanger. Kanske märker du att du
har svårt att tro på att dina nya beteenden kommer att fungera över tid.
Det är helt normalt. Du har förmodligen tänkt dina gamla tankar och
utfört dina säkerhetsbeteenden väldigt länge, så att de numera kommer
helt automatiskt för dig. Det kommer ta lite tid innan det nya
handlandet och dina nya beteenden blir lika automatiserat och självklart
som det gamla har varit. Fortsätt öva så kommer det att automatiseras.

::: {.content-visible when-format="html"}
[Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf)
:::

