---
lang: sv
title: Konstruktiva beteenden för att ge och ta emot komplimanger
---

## Ta emot komplimanger

1.  Se på den andra personen. Sitt eller stå rakryggad. Om du sjunker
    ihop eller inte ser på personen kan det kännas som att du misstror
    eller inte tycker om honom eller henne.
2.  Lyssna på vad personen säger.
3.  Le när du tar emot komplimangen. En komplimang är avsedd att få dig
    att känna dig bra. Om du rynkar ögonbrynen eller tittar ned eller
    undan kan den andra personen bli förvirrad och känna sig obekväm.
4.  Avbryt inte.
5.  Säg ’tack’ eller något annat som visar att du uppskattar det
    personen har sagt.
6.  Kom ihåg att acceptera komplimangen utan att byta ämne från dig
    själv, och utan att tvinga dig att genast betala tillbaka. Det
    hjälper dig att känna dig mer säker och ger dig själv utrymme att
    tycka om dig själv bättre.

### Fler tips för att ta emot komplimanger konstruktivt

-   Övning ger färdighet: Att lära sig ta emot komplimanger kräver aktiv
    övning. Här är en sak som du kan göra för att komma igång direkt.
    Ställ dig framför en spegel. Föreställ dig att någon säger något
    snällt till dig, säg sedan själv: ”Tack så mycket. Det betyder
    mycket för mig.”
-   Byt inte samtalsämne utan att först ha tagit emot och tackat för
    eller erkänt en komplimang.
-   Det är ofta fördelaktigt att använda sig av komplimangen för att
    föra konversationen vidare. ”Tack så mycket! Jag hittade den på
    Blocket -- det är helt otroligt vad man kan hitta där.” På så sätt
    accepterar du både komplimangen och församtalet vidare till något
    som ni båda kan fortsätta prata om.

## Ge komplimanger

Det är också viktigt att lära sig att ge komplimanger. Att ge
komplimanger är ett sätt att visa att du har sett en annan person och
uppskattar honom eller henne eller situationen som ni är tillsammans i.
Människor tycker om att vara tillsammans med andra som är vänliga och
öppna. Det visar också att du har självförtroendet att säga vad du
verkligen tycker -- vilket som du säkert kommer ihåg är en av
hörnstenarna i att hävda sig själv. Ge någon en komplimang, redan idag!

### Steg för att ge komplimanger

-   Tänk ut vad du vill säga när du ger komplimangen. Det hjälper dig så
    här i början, eftersom du slipper söka efter de rätta orden i
    situationen samtidigt som du hanterar obehaget i situationen.
-   Var specifik när du komplimenterar den andra personen. ”Det där
    halsbandet klär dig verkligen” ger ett större intryck än ”du ser
    verkligen bra ut idag”. Ju mer specifik du är, desto bättre är det.
    Det gör att personen känner att du verkligen ser honom eller henne.
-   Mena det du säger, säg det du menar. Människor är ganska bra på att
    känna skillnaden mellan förställning och ärlighet.
-   Överdriv inte. Några meningar räcker. (”Du gjorde ett jättebra jobb
    med ...” eller ”Du lyckades verkligen bra med ...”)
-   Le och visa din entusiasm när du ger en komplimang. Det får den
    andra personen att känna att du verkligen menar det.
-   Känn av situationen. Ta hänsyn till platsen ni befinner er på och
    relationen du har till den andra personen. Att ge en kollega en
    vänlig kommentar om det nyfärgade håret är helt lämpligt, men att
    säga samma sak till högsta chefen skulle kunna vara att gå över
    gränsen.
-   Foga en fråga till din komplimang. Om du vill använda komplimangen
    som en konversationsöppnare, ställ en fråga till mottagaren av din
    komplimang: ”Det där halsbandet är verkligen snyggt på dig. Var har
    du hittat det?”

### Övning: Gör ett beteendeexperiment i tanken

Tänk på ett tillfälle nyligen när du beundrade någon (exempelvis
personens kläder, utförda arbete eller goda handlingar) och du inte gav
henne eller honom en komplimang. Vad skulle du ha velat säga till den
personen? Tänk ut vad du skulle kunna ha sagt till honom eller henne,
och skriv ned det i arbetsbladet. Föreställ dig i din fantasi att du faktiskt hade genomfört experimentet, och se om du då också kan föreställa dig hur utfallet skulle ha blivit. Det är tillåtet -- till och med mycket hjälpsamt -- att öva i fantasin på sådant som är svårt. Det är ett sätt att planera i förväg, som hjälper dig att sedan utföra experimentet i verkligeten, när tillfället uppenbarar sig.

::: {.content-visible when-format="html"}
[Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-beteendeexperiment.pdf)

[Exempel: Planera och genomför ett beteendeexperiment (PDF)](forms/100respekt-exempel-beteendeexperiment.pdf) 
:::