---
lang: sv
title: Sammanfattning och återkoppling på innehållet
---

-   Det är en viktig hävda sig själv-färdighet och en viktig social
    färdighet att kunna ta emot och ge komplimanger.
-   Som med andra färdigheter för konstruktiv självhävdelse kan det
    finnas hindrande tankar som gör det svårt för dig att ta emot en
    komplimang på ett vänligt sätt. Du kan utmana och balansera det
    hindrande tänkandet genom att ge dig tid och struktur för att hitta
    nya, alternativa tankar.
-   Det är också användbart att kunna visa sin vänlighet mot andra genom
    att kunna ge komplimanger.
-   Vi behöver alla regelbundet öva på att ta emot och ge komplimanger.
    Det kan ha en väldigt positiv inverkan på vår egen självkänsla,
    liksom på självkänslan hos dem vi har omkring oss.

::: {.callout-note}
## Hur nära 100 kommer du?

Hur nära 100 kom du när du skattade din självhävdelse i ditt senaste beteendeexperiment? Det finns inte någon inbyggd förväntan på att saker och ting ska ha blivit ”bättre” (eller för all del ”sämre”). Oavsett hur det har gått för dig finns det relevant information att hämta från dina skattningar: Om du skattar din självhävdelse lägre än du hade önskat får du tillfälle att reflektera över vilka hindren i vardagen är, om du skattar din självhävdelse högre får du tillfälle att reflektera över vilka omständigheter som har möjliggjort mer konstruktiv självhävdelse. Kom ihåg: du ”lyckas” eller ”misslyckas” inte med dina beteendeexperiment -- du lär dig något!
:::