project:
  type: book
  output-dir: docs
  pre-render: ./_pre.sh #forms
  post-render: ./_post.sh publish #stage
  
bibliography:
  - ../r2fu/KSH.bib
  - ../r2fu/DBT.bib

book:
  title: "100% respekt"
  output-file: "100respekt"
  author: "Fiona Michel, Anthea Fursland, Patrik Manhem & Tobias Hagberg"
  date: last-modified
  date-format: medium
  favicon: sites/respekt/media/image/100respekt.svg
  sidebar:
    logo: sites/respekt/media/image/100respekt.svg
    collapse-level: 1
    background: light
  cookie-consent: false
  chapters:
    - index.qmd
    - part: "Vecka 1: Introduktion och mål"
      chapters:
        - 1-0.qmd
        - 1-1.qmd
        - 1-2.qmd
        - 1-3.qmd
        - 1-4.qmd
        - 1-5.qmd
        - 1-6.qmd
    - part: "Vecka 2: En grund för nyinlärning"
      chapters:
        - 2-0.qmd
        - 2-1.qmd
        - 2-2.qmd
        - 2-3.qmd
        - 2-4.qmd
        - 2-5.qmd
        - 2-6.qmd
    - part: "Vecka 3: Bli medveten om tänkandet"
      chapters:
        - 3-0.qmd
        - 3-1.qmd
        - 3-2.qmd
        - 3-3.qmd
        - 3-4.qmd
        - 3-5.qmd
        - 3-6.qmd
    - part: "Vecka 4: Bli medveten om handlandet"
      chapters:
        - 4-0.qmd
        - 4-1.qmd
        - 4-2.qmd
        - 4-3.qmd
        - 4-4.qmd
        - 4-5.qmd
        - 4-6.qmd
    - part: "Vecka 5: Bli medveten om kroppen"
      chapters:
        - 5-0.qmd
        - 5-1.qmd
        - 5-2.qmd
        - 5-3.qmd
        - 5-4.qmd
        - 5-5.qmd
        - 5-6.qmd
        - 5-7.qmd
        - 5-8.qmd
    - part: "Vecka 6-7: Säga nej"
      chapters:
        - 6-0.qmd
        - 6-1.qmd
        - 6-2.qmd
        - 6-3.qmd
        - 6-4.qmd
    - part: "Vecka 6-7: Kritik"
      chapters:
        - 7-0.qmd
        - 7-1.qmd
        - 7-2.qmd
        - 7-3.qmd
        - 7-4.qmd
        - 7-5.qmd
        - 7-6.qmd
        - 7-7.qmd
    - part: "Vecka 6-7: Besvikelser"
      chapters:
        - 8-0.qmd
        - 8-1.qmd
        - 8-2.qmd
        - 8-3.qmd
    - part: "Vecka 6-7: Komplimanger"
      chapters:
        - 9-0.qmd
        - 9-1.qmd
        - 9-2.qmd
        - 9-3.qmd
        - 9-4.qmd
        - 9-5.qmd
    - part: "Vecka 8: Planera för framkomlighet"
      chapters:
        - 10-0.qmd
        - 10-1.qmd
        - 10-2.qmd
        - 10-3.qmd
        - 10-4.qmd
        - 10-5.qmd
        - 10-6.qmd
        - 10-7.qmd
    - part: "Resurser"
      chapters:
        - 0-0.qmd
        - 0-1.qmd
        - 0-2.qmd
        - 0-3.qmd

format:
  # epub:
  #   toc: true
  #   number-sections: false
  #   identifier: "1234567890123"
  #   creator: "Tobias Hagberg"
  #   contributor: "Fiona Michel, Anthea Fursland, Patrik Manhem & Tobias Hagberg"
  #   subject: "Psychology"
  #   rights: "Copyright svensk anpassning 2023 Tobias Hagberg & Patrik Manhem"
  html:
    theme:
    - flatly
    - custom.scss
    grid:
      sidebar-width: 333px
    fontsize: 18px
    linestretch: 1.4
    number-sections: false
    collapse-level: 0
  pdf:
    number-sections: false
    keep-tex: true
    pdf-engine: xelatex
    documentclass: book
    classoption: oneside
    toc-depth: 1
    toc-title: "Innehåll"
    lang: sv
    # papersize: a5
    # geometry:
    # - top=30mm
    # - left=20mm
    # - heightrounded
    header-includes: |
      \input{_header_includes.tex}
      \pagestyle{plain}
      \thispagestyle{plain}
      \PassOptionsToPackage{swedish}{babel}
      \PassOptionsToPackage{oneside}{geometry}
      \xinit
      %\twocolumn