---
lang: sv
title: Översikt
format: html
---

## KBT för konstruktiv självhävdelse

Självhävdelse kan vara mer eller mindre konstruktiv, aggressiv eller passiv. Ibland hävdar vi oss inte så konstruktivt som vi skulle önska.

-   Tar du ofta på dig mer än du orkar?
-   Tappar du humöret i trafiken för ofta?
-   Har du svårt att ge eller ta emot komplimanger?
-   Tar det emot att reklamera en vara eller tjänst?
-   Känner du dig ofta stressad och utarbetad?
-   Händer det att du smäller i dörrar när du är arg?
-   Brukar du bli nedstämd efter besvikelser?
-   Har du svårt att säga nej?

Då kan den här självhjälpsmaterialet baserat på kognitiv beteendeterapi (KBT) vara något för dig. I 100% respekt får du lära dig identifiera hindrande tankar och känslor som kan göra det svårt att agera konstruktivt i nära relationer, i arbetet eller gentemot okända personer. Du får också hjälp att själv finna alternativa, konstruktiva beteenden som du utifrån modern psykologisk kunskap och med evidensbaserade metoder får träna på i ditt eget liv. Du kan använda det här materialet på egen hand eller i terapi, med stöd av en KBT-psykolog eller -psykoterapeut. 

Materialet beskrivs och utvärderas vetenskapligt i @HAGBERG2023100629.

::: {.content-visible when-format="html"}
<div class="hanging-indent" role="list">
<div id="ref-HAGBERG2023100629" class="csl-entry" role="listitem">
Hagberg, Tobias, Patrik Manhem, Martin Oscarsson, Fiona Michel, Gerhard
Andersson, and Per Carlbring. 2023. <span>“Efficacy of Transdiagnostic
Cognitive-Behavioral Therapy for Assertiveness: A Randomized Controlled
Trial.”</span> <em>Internet Interventions</em> 32: 100629. <a href="https://doi.org/10.1016/j.invent.2023.100629">https://doi.org/10.1016/j.invent.2023.100629</a>.
</div>
</div>
:::

## 10 avsnitt, 8 veckor

KBT-självhjälpsmaterialet består av 10 avsnitt som det är tänkt att du jobbar med under loppet av 8 veckor. Under de första fem veckorna kommer du att ...

- [sätta meningsfulla personliga mål](1-0.qmd)\xpageref{sec-myths},
- [lära dig om konstruktiv självhävdelse](2-0.qmd)\xpageref{sec-assertiveness},
- [lära dig tänka mer flexibelt](3-0.qmd)\xpageref{sec-thinking},
- [bli varse vilket handlande som är ändamålsenligt](4-0.qmd)\xpageref{sec-behaviour} samt att
- [bli medveten om och hantera kroppsliga stressreaktioner](5-0.qmd)\xpageref{sec-relaxation}.

Under de två näst sista veckorna väljer du själv vilka fördjupningsområden du vill jobba med: Att bli bättre på att klara av att ...

- [säga nej till sådant som du egentligen inte själv vill](6-0.qmd)\xpageref{sec-sayno}, 
- [ta och ge kritik](7-0.qmd)\xpageref{sec-critique}, 
- [hantera besvikelser](8-0.qmd)\xpageref{sec-disappointments} eller att
- [ta och ge komplimanger](9-0.qmd)\xpageref{sec-compliments}.

Under den sista veckan sätter du ihop din personliga [plan för fortsatt träning](10-0.qmd)\xpageref{sec-maintenance}.

## Syftet med det här materialet

Det övergripande syftet med 100% respekt är att hjälpa dig att hitta större framkomlighet i livet genom att öka graden av konstruktivt hävdande av tankar, känslor, önskemål, behov och gränser. Med ”konstruktiv självhävdelse” menas kort sagt handlande som respekterar dina egna rättigheter att hävda dig och som samtidigt respekterar andra människors motsvarande rättigheter. Om du når ända fram i båda avseenden blir det 10 × 10 = 100!

Redo att börja?
