---
lang: sv
title: "Uppgift: Formulera ett första mål för träningsprogrammet"
---

Under de kommande veckorna kommer du att få träna på att hävda dig själv
konstruktivt i situationer som brukar bli besvärliga. Vilket område vill
du börja träna inom? Du kommer strax att få formulera en egen
målsättning.

Om du inte redan har tittat på den här filmsnutten -- gör det nu!

## Vad är ett "SMART" mål?

När du nu formulerar ditt eget mål, använd formeln "SMART". Med det
menas målet så långt det är möjligt bör vara S) specifikt, M) mätbart,
A) acceptabelt (i meningen nåbart, *attainable* på engelska), R) realistiskt och T) tidssatt.
Här är några exempel på mer eller mindre SMARTa målsättningar:

-   *"Mitt mål är att säga nej till min chef när hen frågar om jag kan
    arbeta över på onsdagar och torsdagar under de kommande 8
    veckorna."*
    -   S? Är målet specifikt? Ja!
    -   M? Är det mätbart? Ja, det går att räkna antal gånger personen
        säger nej till chefen.
    -   A? Är det nåbart? Ja, om du har formellt mandat att säga ifrån.
    -   R? Är det realistiskt? Ja, om det är sannolikt att chefen
        faktiskt kommer att be personen att jobba över.
    -   T? Är det tidssatt? Ja, det gäller vissa dagar (onsdagar och
        torsdagar) under en begränsad tid (8 veckor).
-   *"Mitt mål är att säga \'Jag älskar dig\' till min partner 3 gånger
    under veckan som kommer"*
    -   Utvärdera själv om målet är SMART!
-   *"Mitt mål är att under de kommande 4 veckorna knacka på hos
    grannen och att utan att tappa humöret och börja skälla förklara att
    jag har svårt att sova på grund av den höga ljudvolymen, varje gång
    grannen spelar högt på stereon efter 22:30 på vardagskvällar"*
    -   Utvärdera själv om målet är SMART!
-   *"Mitt mål är att sluta vara så mesig och att sluta ha så mycket ångest i sociala
    sammanhang"*
    -   Tänk efter -- tycker du att det här målet var särskilt SMART?
        Varför inte?

När du formulera ditt mål på formeln SMART gör du det det möjligt för dig själv
att märka när du har uppnått det. Det kopplar loss utvärderingen från "hur det
känns" -- ibland kan man framgångsrikt göra något svårt och viktigt fast det
inte alls känns roligt när man gör det. Ett SMART mål gör det på så sätt möjligt
för dig att registrera både bakslag och framgångar med lite distans till
känslorna. Kanske känns det provocerande att minska betydelsen av känslorna. Kom
då ihåg att det på inget sätt betyder att känslorna är oviktiga. Anledningen är
helt pragmatiskt: för att klara av att börja träna på en färdighet som är
förenlig med något du själv tycker är viktigt kan det ofta vara hjälpsamt att
sätta känslorna lite åt sidan till en början. Beteenden är trots allt väldigt
mycket lättare att förändra än känslor. Genom att göra det du behöver kan du på
lite längre sikt också förändra de känslomässiga aspekterna av upplevelsen.
Under programmet kommer du att få hjälp med att hantera både mot- och medgångar
(såväl praktiska som känslomässiga) på ett sätt som ökar chansen att du kommer
att orka fortsätta träna på det som du tycker är både viktigt och svårt.

## Din egen målsättning

Nu är det din tur! Ta hjälp av kartläggningen du gjorde nyss, och
formulera ett helt eget mål för behandlingen. Ge dig själv lite tid att
hitta ett mål som är lagom svårt -- med det menas att det ska vara just
realistiskt, men samtidigt utmanande och aningen ångestväckande. Det är
när du handlar på ett sätt som du vill, trots visst obehag, som du ger
dig själv en chans till nyinlärning och kan bredda din
beteenderepertoar.

<!-- ##4f1b5b6c8b7a92eb516892f5f44e84e7= -->

```{=html}
<div id="form-div" class="form-wrapper">
<form id="note-form">
<div class="form-group">
<textarea name="4f1b5b6c8b7a92eb516892f5f44e84e7" id="textarea1" rows="6" class="form-control"></textarea>
</div>
<br>
<div class="form-group">
  <input type="submit" id="note-submit" value="Spara" class="btn btn-primary">
</div>
</form></div>
<br>
<div class="alert alert-dismissible alert-success" style="display:hidden;">
Formuläret sparas på din enhet
</div>

<script>
// form.js
const formId = "note-form"; // ID of the form
const url = location.href; //  href for the page
const formIdentifier = `${url} ${formId}`; // Identifier used to identify the form
const saveButton = document.querySelector("#note-submit"); // select save button
const alertBox = document.querySelector(".alert"); // select alert display div
let form = document.querySelector(`#${formId}`); // select form
let formElements = form.elements; // get the elements in the form

/**
 * This function gets the values in the form
 * and returns them as an object with the
 * [formIdentifier] as the object key
 * @returns {Object}
 */
const getFormData = () => {
  let data = { [formIdentifier]: {} };
  for (const element of formElements) {
    if (element.name.length > 0) {
      data[formIdentifier][element.name] = element.value;
    }
  }
  return data;
};

saveButton.onclick = event => {
  event.preventDefault();
  data = getFormData();
  localStorage.setItem(formIdentifier, JSON.stringify(data[formIdentifier]));
  const message = "Formuläret sparat på din enhet";
  displayAlert(message);
};

/**
 * This function displays a message
 * on the page for 1 second
 *
 * @param {String} message
 */
const displayAlert = message => {
  alertBox.innerText = message;
  alertBox.style.display = "block";
  setTimeout(function() {
    alertBox.style.display = "none";
  }, 3000);
};

/**
 * This function populates the form
 * with data from localStorage
 *
 */
const populateForm = () => {
  if (localStorage.key(formIdentifier)) {
    const savedData = JSON.parse(localStorage.getItem(formIdentifier)); // get and parse the saved data from localStorage
    for (const element of formElements) {
      if (element.name in savedData) {
        element.value = savedData[element.name];
      }
    }
    const message = "Formuläret uppdaterat";
    displayAlert(message);
  }
};

document.onload = populateForm(); // populate the form when the document is loaded
</script>
```

Dina svar sparas enbart på den enhet som du använder just nu (ingen data skickas över nätet).