---
lang: sv
title: Din måluppfyllelse just nu
---

Du formulerade i modul 1 en första personlig målsättning för programmet.
Du skrev så här:

##4f1b5b6c8b7a92eb516892f5f44e84e7=

## Hur väl tycker du att du just ny lever upp till målet?

Gör en ny skattning för hur det är för dig just den här veckan. Det
finns inte någon inbyggd förväntan på att saker och ting ska ha blivit
"bättre" (eller för all del "sämre") här. Oavsett hur det har gått
för dig finns det relevant information att hämta från dina skattningar:
Om du skattar din självhävdelse lägre får du tillfälle att reflektera
över vilka hindren i vardagen är, om du skattar din självhävdelse högre
får du tillfälle att reflektera över vilka omständigheter som har
möjliggjort mer konstruktiv självhävdelse.

##3cfbe1d73d114272b3639c9cabcdabff=

## Vad drar du för slutsatser?

##28e2d94f46eeb8b5b4b9402834c18e89=

## Utvärdering av den här modulen

##371ab23fa17caec70eac1edb1806eb03=

## Om nästa modul

I nästa modul tittar vi närmare på vanliga tankemönster, som kan hindra
oss från att hävda oss själva. Vi lär oss också hur vi kan balansera
dessa med konstruktivt tänkande. Vi fortsätter också med del 2 i
progressiv avslappning.

Med respekt i kvadrat,

/Patrik & Tobias
