---
title: "Hjälpande antaganden om att säga ’nej’"
engine: knitr
format:
  pdf:
    keep-tex: true
    pdf-engine: xelatex
    documentclass: article
    lang: sv
header-includes: 
- \input{../_header_includes.tex}
bibliography:
  - ../../r2fu/KSH.bib
  - ../../r2fu/DBT.bib
csl: ../apa.csl
---

\xinit

Hindrande tankar är inte fakta. De är helt enkelt bara förutsägelser och åsikter som vi har lärt oss eller räknat ut. Var och en av dem kan vägas mot en mer hjälpsam förutsägelse eller åsikt om vikten av konstruktiv självhävdelse, exempelvis att säga ’nej’ till sådant som du inte vill ställa upp på. I listan nedan finns några förslag på hjälpsamma antaganden. Kryssa för dem som du håller med om, och komplettera med ytterligare antaganden som du kan komma på om nyttan med att hävda dig själv bättre.

\setlist[itemize]{
    label={\xtikztick}
}

- Andra människor har rätt att fråga, och jag har rätt att neka en fråga.
- När jag säger ’nej’ nekar jag till en begäran, inte personen framför mig.
- När jag säger ’ja’ till en sak säger jag faktiskt också ’nej’ till något annat. Jag har alltid en valmöjlighet, och jag gör val hela tiden.
- Människor som har svårt att säga ’nej’ överskattar ofta svårigheten som den andra personen skulle ha att acceptera ett nekande svar. Vi litar inte på att de klarar av att höra ett ’nej’. Genom att vi uttrycker våra känslor öppet och fritt kan vi faktiskt hjälpa den andra personen att uttrycka sina känslor. När vi säger ’nej’ till någon visar vi att också de kan säga ’nej’ till dina frågor – samtidigt som frågan även fortsättningsvis är fri.

\xfline{Fler hjälpande antaganden som jag kan komma på}{8}{}

{{< include _pdf_footer.qmd >}}