---
title: "Planera för framgång"
engine: knitr
format:
  pdf:
    keep-tex: true
    pdf-engine: xelatex
    documentclass: article
    lang: sv
header-includes: 
- \input{../_header_includes.tex}
bibliography:
  - ../../r2fu/KSH.bib
  - ../../r2fu/DBT.bib
---

\xinit

Hur kan du optimera dina odds att utföra beteendet "träna på progressiv avslappning" eller beteendet "träna medveten närvaro"?

- *Var* gör du bäst övningarna? (Hemma? I bussen hem från jobbet? I vilorummet på jobbet? En bänk utmed promenadslingan?)
- *När* kan du ge dig själv 15 minuter? Vilka dagar under veckan som kommer? Vilken tid på dygnet? Behöver du välja bort något annat? (TV-serier? Övertidsarbete?)
- *Vad* vill du göra för att hjälpa dig själv att komma igång? (Ta hjälp av en vän? Planera med din partner? Din chef?)

Kort och gott: skriv ned din plan för träning i avslappning och/eller medveten närvaro under den kommande veckan. Formulera dig så specifikt du kan, gärna på formen SMART -- specifikt, mätbart, acceptabelt, realitiskt och tidssatt. Ett exempel: "Jag vill schemalägga att träna progressiv avslappning 15 minuter varje morgon, innan jag dricker morgonkaffet, under de kommande 5 dagarna. Jag ställer in en påminnelse på mobilen för att komma ihåg träningen."

\xfline{Min träningsplan för veckan om kommer}{8}{}

{{< include _pdf_footer.qmd >}}