---
title: "Hindrande antaganden om att hantera besvikelser"
engine: knitr
format:
  pdf:
    keep-tex: true
    pdf-engine: xelatex
    documentclass: article
    lang: sv
header-includes: 
- \input{../_header_includes.tex}
bibliography:
  - ../../r2fu/KSH.bib
  - ../../r2fu/DBT.bib
---

\xinit

Kan du identifiera några exempel på tänkande som hindrar dig i situationer där
vill kunna hantera besvikelser på ett konstruktivt sätt? Kryssa
för dem som du känner igen dig i nedan. Ge dig också själv lite tid att försöka
sätta ord på ytterligare antaganden som hindrar dig. Även om det kan vara
skrämmande att se ditt tänkande på pränt, påminn dig om att de är just det --
tankar. Du kommer i när du arbetar vidare få möjlighet att förhålla dig friare
och mer flexibelt till dem.

\setlist[itemize]{
    label={\xtikztick}
}

- De borde veta att jag inte gillar när de gör så där.
- Världen är hemsk, jag står inte ut med det här.
- Den personen är ond.
- Jag vägrar acceptera att den personen gör på det sättet.
- Jag tolererar inte det här, det är oacceptabelt.

\xfline{Fler hindrande antaganden som jag märker att jag följer}{8}{}

{{< include _pdf_footer.qmd >}}