---
title: "Hjälpande antaganden om att ta/ge kritik"
engine: knitr
format:
  pdf:
    keep-tex: true
    pdf-engine: xelatex
    documentclass: article
    lang: sv
header-includes: 
- \input{../_header_includes.tex}
bibliography:
  - ../../r2fu/KSH.bib
  - ../../r2fu/DBT.bib
---

\xinit

Hindrande tankar är inte fakta. De är helt enkelt bara förutsägelser och åsikter som vi har lärt oss eller räknat ut. Var och en av dem kan vägas mot en mer hjälpsam förutsägelse eller åsikt om vikten av konstruktiv självhävdelse, exempelvis att ta och ge kritik på ett konstruktivt sätt. I listan nedan finns några förslag på hjälpsamma antaganden. Kryssa för dem som du håller med om, och komplettera med ytterligare antaganden som du kan komma på om nyttan med att hävda dig själv bättre.

\setlist[itemize]{
    label={\xtikztick}
}

- Om det är något fel på det jag gjort betyder det inte något om mig som person. Jag behöver skilja mellan mitt handlande och mig själv som person.
- Vad kan jag lära mig av kritiken? Det mesta av kritiken innehåller sannolikt ett korn av sanning. Kritik kan te sig negativt. Men varje gång jag får kritik har jag möjlighet att lära mig av den. Jag kan vill alltid fråga mig själv vad jag kan lära mig av kritiken.
- Jag har rätt att berätta att jag känner mig sårad, irriterad eller upprörd, av andras beteende.
- Att ge direkt återkoppling och kritik kan vara kärleksfullt och omtänksamt.

\xfline{Fler hjälpande antaganden som jag kan komma på}{8}{}

{{< include _pdf_footer.qmd >}}