---
title: "Hindrande antaganden"
format:
  pdf:
    keep-tex: true
    pdf-engine: xelatex
    documentclass: article
    lang: sv
header-includes: 
- \input{../_header_includes.tex}
bibliography:
  - ../../r2fu/KSH.bib
  - ../../r2fu/DBT.bib
---

\xinit

Kan du identifiera några exempel på tänkande som hindrar dig i situationer där
du skulle vilja kunna hävda dina behov, önskemål eller gränser bättre? Kryssa
för dem som du känner igen dig i nedan. Ge dig också själv lite tid att försöka
sätta ord på ytterligare antaganden som hindrar dig. Även om det kan vara
skrämmande att se ditt tänkande på pränt, påminn dig om att de är just det --
tankar. Du kommer i när du arbetar vidare få möjlighet att förhålla dig friare
och mer flexibelt till dem.

\setlist[itemize]{
    label={\xtikztick}
}

- Jag borde inte säga vad jag verkligen känner eller tänker eftersom jag inte vill tynga ned andra med mina problem.
- Om jag hävdar mig själv kommer den andra personen att bli upprörd och det kommer förstöra vår relation.
- Det blir bara hemskt pinsamt om jag säger vad jag tänker.
- Om någon säger ’nej’ till min begäran är det för att personen inte tycker om mig eller älskar mig.
- Jag borde inte behöva säga vad jag behöver eller hur jag känner: Människor som står nära mig borde redan veta vad det är.
- Att säga vad man tycker visar att man inte bryr sig om andra, det är oförskämt och själviskt.
- Jag har ingen rätt att ändra mig i en fråga; det har inte andra heller.
- Det löser sig på något sätt ändå, och hur som helst är det inte mitt ansvar.
- Folk ska hålla sina känslor för sig själva.
- Om jag visar att jag har ångest kommer andra människor tycka att jag är svag och förlöjliga eller utnyttja mig.
- Om jag tar emot och accepterar en komplimang från någon betyder det att jag förhäver mig själv.

\xfline{Fler hindrande antaganden som jag märker att jag följer}{6}{}

{{< include ../_pdf_footer.qmd >}}