---
title: "Manus för progressiv avslappning"
format:
  pdf:
    keep-tex: true
    pdf-engine: xelatex
    documentclass: article
    lang: sv
header-includes: 
- \input{../_header_includes.tex}
bibliography:
  - ../../r2fu/KSH.bib
  - ../../r2fu/DBT.bib
---

\xinit

Till att börja med, sätt dig bekvämt i en stol. Det är bättre att göra övningarna sittandes än liggandes, så att du inte råkar somna. Hela övningen bör ta cirka 15 till 20 minuter. Sätt båda fötterna på golvet och låt händerna vila i knät. Låt dina ögonlock falla ned så att dina ögon sluts lätt. Lägg märke till tyngden av din kropp, ditt huvud, dina axlar, dina armar och dina ben. **Observera! Under övningen, se till att du slappnar av dubbelt så länge som du spänner dig.**

1. Knyt höger hand, och lägg märke till spänningen medan du gör det. Kläm åt lite hårdare och känn spänningen i näven, handleden och underarmen. Släpp taget och låt din hand slappna av. Notera skillnaden i spänning och hur avslappningen känns. Upprepa detta med höger hand en gång. Upprepa sedan allt igen, med vänster hand. Spänn och slappna sedan av i båda händerna samtidigt.

2. Gå vidare till underarmen, genom att böja din hand framåt och nedåt. Låt sedan musklerna slappna av genom att räta upp handleden igen. Lägg märke till hur avslappningen känns. Upprepa med den andra underarmen.

3. Spänn dina båda biceps-muskler genom att pressa underarmarna upp mot dem. Spänn dem så hårt du kan. Känn spänningen. Slappna sedan av genom att räta ut armarna. Lägg märke till hur avslappningen känns. Repetera.

4. Flytta uppmärksamheten till axlarna. Spänn dina axlar genom att lyfta upp dem, som om du försökte nudda öronen med dem. Slappna sedan av genom att låta dem sjunka ned igen, uppmärksamma avslappningen. Upprepa en gång.

5. Med armarna hängande utmed sidorna, tryck axlarna framåt. Håll så i 10 sekunder och slappna sedan av genom att låta axlarna gå tillbaka till sitt naturliga läge. Lägg märke till hur avslappningen känns.

6. Låt uppmärksamheten gå till din nacke. Om du har ont i nacken eller har dragit på dig en nackskada, fråga först din läkare eller fysioterapeut innan du gör den här övningen. Luta försiktigt huvudet till vänster tills dess att du känner att musklerna på höger sida av nacken spänns. Rulla sakta huvudet framåt och till höger, och sedan sakta igen tillbaka till vänster. Den här övningen ska inte göra ont. Om du känner smärta sträcker du musklerna för mycket, då behöver du ta det lite försiktigare. Upprepa en gång.

7. Flytta uppmärksamheten till huvudet. Gör pannan så rynkig som det går. Det kan hjälpa att lyfta på ögonbrynen. Håll så i 10 sekunder, och slappna sedan av. Lägg märke till avslappningen.

8. Slut dina ögon hårt och håll spänningen i 10 sekunder. Slappna av och känn hur det känns. Upprepa en gång.

9. Bit samman käkarna i 10 sekunder. Släpp det hårda bettet och låt käkmusklerna slappna av. När du slappnar av helt i käken är dina läppar något särade. Lägg noga märke till skillnaden mellan muskelspänning och -avslappning. Upprepa en gång.

10. Pressa tungan hårt mot gommen. Slappna sedan av och låt tungan falla ned igen. Upprepa.

11. Pressa samman läpparna och forma dem till ett “O”. Slappna sedan av i läpparna. Repetera. Se till att resten av ansiktet fortfarande är avslappnat.

12. Flytta uppmärksamheten till bröstet. Andas in och fyll dina lungor helt samtidigt som du spänner bröstmusklerna. Håll andan i 10 sekunder innan du andas ut helt och låter musklerna slappna av. Töm lungorna helt innan du tar nästa andetag. Lägg märke till hur avslappningen känns. Repetera en gång.

\xturn

13. Gå vidare till magen. Spänn magmusklerna och håll. Lägg märke till hur spänningen känns och slappna sedan av. Placera din hand på magen. Andas in djupt, med magen, så att handen på magen rör sig framåt när du andas in. Håll och slappna sedan av. Upprepa en gång.

14. Forma ryggen till en båge. Känn spänningen i ländryggen, den nedre delen av ryggen. Håll och slappna sedan av, och räta på dig till sittande ställningen igen. Upprepa en gång.

15. Spänn skinkorna i rumpan genom att pressa ihop dem. När du gör det ska du komma lite högre upp i stolen. Håll och slappna sedan av. Lägg märke till hur avslappningen känns. Upprepa en gång.

16. Fortsätt genom att flytta uppmärksamheten till benen. Spänn låren genom att trycka ned hälarna i golvet, så hårt du kan. Håll och slappna sedan av. Upprepa en gång.

17. Spänn dina vader genom att lyfta tårna upp mot smalbenet. Håll och slappna sedan av. Upprepa en gång.

18. Spänn dina fötter genom att rulla in tårna mot golvet. Håll och slappna sedan av. Lägg märke till hur avslappningen känns. Upprepa en gång.

När du har gått genom alla muskelgrupper är det en god idé att sitta still några minuter för att verkligen känna hur det känns att vara avslappnad. Res inte på dig för snabbt, eftersom det kan göra att du återgår till det spända läget. När du slappnar av sjunker dessutom ditt blodtryck, så om du reser dig för snabbt kan du bli lite yr.

{{< include ../_pdf_footer.qmd >}}